-- Seed script for Ilmu Pengetahuan Alam (IPA) curriculum
-- Language: Indonesian
-- Curriculum Type: Kurikulum Merdeka Belajar

-- Clear existing IPA data to prevent duplicates
DELETE FROM public.curriculum WHERE subject = 'Ilmu Pengetahuan Alam (IPA)';

-- Grade 7
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Hakikat Ilmu Sains dan Metode Ilmiah', 'Cabang Ilmu Sains'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Hakikat Ilmu Sains dan Metode Ilmiah', 'Karakteristik Sains'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Hakikat Ilmu Sains dan Metode Ilmiah', 'Langkah Metode Ilmiah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Hakikat Ilmu Sains dan Metode Ilmiah', 'Penerapan Metode Ilmiah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Zat dan Perubahannya', 'Wujud Zat dan Model Partikel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Zat dan Perubahannya', 'Perubahan Wujud Zat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Zat dan Perubahannya', 'Perubahan Fisika vs. Kimia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Zat dan Perubahannya', 'Kerapatan Zat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Suhu, Kalor, dan Pemuaian', 'Pengertian Suhu dan Termometer'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Suhu, Kalor, dan Pemuaian', 'Kalor'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Suhu, Kalor, dan Pemuaian', 'Perpindahan Kalor'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Suhu, Kalor, dan Pemuaian', 'Pemuaian'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Gerak dan Gaya', 'Konsep Gerak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Gerak dan Gaya', 'Jenis Gerak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Gerak dan Gaya', 'Besaran dalam Gerak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Gerak dan Gaya', 'Gaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Klasifikasi Makhluk Hidup', 'Ciri-Ciri Makhluk Hidup dan Benda Mati'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Klasifikasi Makhluk Hidup', 'Tujuan dan Manfaat Klasifikasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Klasifikasi Makhluk Hidup', 'Sistem Klasifikasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Klasifikasi Makhluk Hidup', 'Urutan Takson'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Klasifikasi Makhluk Hidup', 'Kunci Determinasi Sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Ekologi dan Keanekaragaman Hayati', 'Pengertian Ekosistem'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Ekologi dan Keanekaragaman Hayati', 'Interaksi Antarkomponen Ekosistem'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Ekologi dan Keanekaragaman Hayati', 'Rantai Makanan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Ekologi dan Keanekaragaman Hayati', 'Aliran Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Ekologi dan Keanekaragaman Hayati', 'Perubahan Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Ekologi dan Keanekaragaman Hayati', 'Keanekaragaman Hayati'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Ekologi dan Keanekaragaman Hayati', 'Pelestarian Keanekaragaman Hayati'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 7: Sistem Tata Surya', 'Pengenalan Tata Surya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 7: Sistem Tata Surya', 'Planet-Planet'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 7: Sistem Tata Surya', 'Gerak Rotasi dan Revolusi Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 7: Sistem Tata Surya', 'Gerak Bulan dan Fase-fasenya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 7: Sistem Tata Surya', 'Gaya Gravitasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 7: Sistem Tata Surya', 'Pengaruh Suhu dan Radiasi Matahari');

-- Grade 8
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pengenalan Sel', 'Pengertian Sel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pengenalan Sel', 'Mikroskop'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pengenalan Sel', 'Struktur dan Fungsi Sel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pengenalan Sel', 'Perbedaan Sel Hewan dan Tumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pengenalan Sel', 'Organel-organel Sel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pengenalan Sel', 'Spesialisasi Sel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Struktur dan Fungsi Tubuh Makhluk Hidup', 'Zat Gizi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Struktur dan Fungsi Tubuh Makhluk Hidup', 'Sistem Pencernaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Struktur dan Fungsi Tubuh Makhluk Hidup', 'Sistem Peredaran Darah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Struktur dan Fungsi Tubuh Makhluk Hidup', 'Sistem Pernapasan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Struktur dan Fungsi Tubuh Makhluk Hidup', 'Sistem Ekskresi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Usaha, Energi, dan Pesawat Sederhana', 'Pengertian Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Usaha, Energi, dan Pesawat Sederhana', 'Konsep Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Usaha, Energi, dan Pesawat Sederhana', 'Hukum Kekekalan Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Usaha, Energi, dan Pesawat Sederhana', 'Pesawat Sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Getaran, Gelombang, dan Cahaya', 'Konsep Dasar Getaran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Getaran, Gelombang, dan Cahaya', 'Gelombang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Getaran, Gelombang, dan Cahaya', 'Perambatan Gelombang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Getaran, Gelombang, dan Cahaya', 'Sifat Cahaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Getaran, Gelombang, dan Cahaya', 'Cermin dan Lensa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Unsur, Senyawa, dan Campuran', 'Unsur'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Unsur, Senyawa, dan Campuran', 'Senyawa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Unsur, Senyawa, dan Campuran', 'Campuran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Unsur, Senyawa, dan Campuran', 'Perbedaan Unsur, Senyawa, dan Campuran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Unsur, Senyawa, dan Campuran', 'Pemisahan Campuran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 6: Struktur Bumi dan Perkembangannya', 'Struktur Lapisan Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 6: Struktur Bumi dan Perkembangannya', 'Lempeng Tektonik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 6: Struktur Bumi dan Perkembangannya', 'Gempa Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 6: Struktur Bumi dan Perkembangannya', 'Gunung Api'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 6: Struktur Bumi dan Perkembangannya', 'Dampak Perubahan Geologi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Struktur dan Fungsi Tubuh Makhluk Hidup', 'Sistem Pernapasan Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Struktur dan Fungsi Tubuh Makhluk Hidup', 'Sistem Ekskresi Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Struktur dan Fungsi Tubuh Makhluk Hidup', 'Proses Ekskresi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Struktur dan Fungsi Tubuh Makhluk Hidup', 'Gangguan dan Penyakit'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Usaha, Energi, dan Pesawat Sederhana', 'Konsep Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Usaha, Energi, dan Pesawat Sederhana', 'Jenis-jenis Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Usaha, Energi, dan Pesawat Sederhana', 'Perubahan Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Usaha, Energi, dan Pesawat Sederhana', 'Pesawat Sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Usaha, Energi, dan Pesawat Sederhana', 'Keuntungan Mekanis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Getaran, Gelombang, dan Cahaya', 'Getaran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Getaran, Gelombang, dan Cahaya', 'Gelombang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Getaran, Gelombang, dan Cahaya', 'Perambatan Gelombang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Getaran, Gelombang, dan Cahaya', 'Cahaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Getaran, Gelombang, dan Cahaya', 'Alat Optik Sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 4: Unsur, Senyawa, dan Campuran', 'Unsur'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 4: Unsur, Senyawa, dan Campuran', 'Senyawa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 4: Unsur, Senyawa, dan Campuran', 'Campuran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 4: Unsur, Senyawa, dan Campuran', 'Pemisahan Campuran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 4: Unsur, Senyawa, dan Campuran', 'Perbandingan Unsur, Senyawa, Campuran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Struktur Bumi dan Perkembangannya', 'Struktur Lapisan Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Struktur Bumi dan Perkembangannya', 'Lempeng Tektonik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Struktur Bumi dan Perkembangannya', 'Gempa Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Struktur Bumi dan Perkembangannya', 'Gunung Berapi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Struktur Bumi dan Perkembangannya', 'Pengaruh Aktivitas Geologi');

-- Grade 9
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Perbedaan Pertumbuhan dan Perkembangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Siklus Hidup Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Masa Pubertas'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Perkembangan Embrio Hewan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Perkembangan Tumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Sistem Koordinasi, Reproduksi, dan Homeostasis', 'Sistem Saraf'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Sistem Koordinasi, Reproduksi, dan Homeostasis', 'Sistem Hormon'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Sistem Koordinasi, Reproduksi, dan Homeostasis', 'Sistem Reproduksi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Sistem Koordinasi, Reproduksi, dan Homeostasis', 'Mekanisme Homeostasis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Tekanan', 'Konsep Tekanan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Tekanan', 'Tekanan Hidrostatis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Tekanan', 'Aplikasi Tekanan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Tekanan', 'Tekanan Udara'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Listrik, Magnet, dan Sumber Energi Alternatif', 'Listrik Statis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Listrik, Magnet, dan Sumber Energi Alternatif', 'Listrik Dinamis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Listrik, Magnet, dan Sumber Energi Alternatif', 'Rangkaian Listrik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Listrik, Magnet, dan Sumber Energi Alternatif', 'Kemagnetan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Listrik, Magnet, dan Sumber Energi Alternatif', 'Sumber Energi Alternatif'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Reaksi Kimia', 'Ciri-Ciri Reaksi Kimia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Reaksi Kimia', 'Reaktan dan Produk'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Reaksi Kimia', 'Jenis Reaksi Kimia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Reaksi Kimia', 'Faktor Laju Reaksi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 6: Pewarisan Sifat dan Bioteknologi', 'Struktur Dasar Pewarisan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 6: Pewarisan Sifat dan Bioteknologi', 'Hukum Mendel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 6: Pewarisan Sifat dan Bioteknologi', 'Pewarisan Sifat Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 6: Pewarisan Sifat dan Bioteknologi', 'Pemuliaan Makhluk Hidup'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 6: Pewarisan Sifat dan Bioteknologi', 'Bioteknologi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 7: Isu-Isu Lingkungan', 'Pengertian Isu Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 7: Isu-Isu Lingkungan', 'Faktor Kerusakan Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 7: Isu-Isu Lingkungan', 'Sifat Tanah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 7: Isu-Isu Lingkungan', 'Upaya Pelestarian Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Sistem Reproduksi dan Perkembangbiakan', 'Sistem Reproduksi Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Sistem Reproduksi dan Perkembangbiakan', 'Kesehatan Reproduksi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Sistem Reproduksi dan Perkembangbiakan', 'Perkembangbiakan Tumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Sistem Reproduksi dan Perkembangbiakan', 'Perkembangbiakan Hewan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pewarisan Sifat dan Bioteknologi', 'Konsep Pewarisan Sifat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pewarisan Sifat dan Bioteknologi', 'Hukum Mendel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pewarisan Sifat dan Bioteknologi', 'Kelainan Genetik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pewarisan Sifat dan Bioteknologi', 'Bioteknologi Konvensional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pewarisan Sifat dan Bioteknologi', 'Bioteknologi Modern'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Listrik dan Magnet', 'Listrik Statis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Listrik dan Magnet', 'Listrik Dinamis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Listrik dan Magnet', 'Kemagnetan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Listrik dan Magnet', 'Induksi Elektromagnetik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Listrik dan Magnet', 'Interaksi Listrik dan Magnet'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Usaha, Energi, dan Pesawat Sederhana', 'Konsep Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Usaha, Energi, dan Pesawat Sederhana', 'Jenis Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Usaha, Energi, dan Pesawat Sederhana', 'Hukum Kekekalan Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Usaha, Energi, dan Pesawat Sederhana', 'Pesawat Sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Reaksi Kimia dan Perubahan Materi', 'Jenis Reaksi Kimia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Reaksi Kimia dan Perubahan Materi', 'Tanda-Tanda Reaksi Kimia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Reaksi Kimia dan Perubahan Materi', 'Faktor Laju Reaksi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Reaksi Kimia dan Perubahan Materi', 'Partikel Penyusun Zat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Reaksi Kimia dan Perubahan Materi', 'Model Atom'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 6: Isu dan Solusi Lingkungan', 'Isu Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 6: Isu dan Solusi Lingkungan', 'Dampak Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 6: Isu dan Solusi Lingkungan', 'Teknologi Ramah Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 6: Isu dan Solusi Lingkungan', 'Peran Individu dan Komunitas');

-- Grade 10
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 1: Pengukuran dalam Kerja Ilmiah', 'Konsep Dasar Pengukuran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 1: Pengukuran dalam Kerja Ilmiah', 'Satuan Internasional (SI)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 1: Pengukuran dalam Kerja Ilmiah', 'Ketelitian, Ketepatan, Kesalahan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 1: Pengukuran dalam Kerja Ilmiah', 'Alat Ukur'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 2: Virus dan Peranannya', 'Struktur dan Jenis Virus'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 2: Virus dan Peranannya', 'Reproduksi Virus'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 2: Virus dan Peranannya', 'Peran Virus'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 2: Virus dan Peranannya', 'Pencegahan Infeksi Virus'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Kimia Hijau', 'Prinsip-Prinsip Kimia Hijau'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Kimia Hijau', 'Bahan Ramah Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Kimia Hijau', 'Pengolahan Limbah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Kimia Hijau', 'Penerapan Kimia Hijau'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 4: Hukum Dasar Kimia', 'Hukum Kekekalan Massa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 4: Hukum Dasar Kimia', 'Hukum Perbandingan Tetap'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 4: Hukum Dasar Kimia', 'Hukum Perbandingan Berganda'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 4: Hukum Dasar Kimia', 'Aplikasi Hukum Dasar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 5: Struktur Atom', 'Model Atom'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 5: Struktur Atom', 'Partikel Dasar Atom'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 5: Struktur Atom', 'Nomor Atom dan Massa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 5: Struktur Atom', 'Isotop, Isoton, Isobar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 6: Energi Terbarukan', 'Sumber Energi Terbarukan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 6: Energi Terbarukan', 'Mekanisme Pemanfaatan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 6: Energi Terbarukan', 'Kelebihan dan Kekurangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 6: Energi Terbarukan', 'Dampak Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 7: Keanekaragaman Hayati dan Perubahan Iklim', 'Konsep Keanekaragaman Hayati'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 7: Keanekaragaman Hayati dan Perubahan Iklim', 'Jenis Ekosistem'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 7: Keanekaragaman Hayati dan Perubahan Iklim', 'Penyebab dan Dampak Perubahan Iklim'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 1', 'Bab 7: Keanekaragaman Hayati dan Perubahan Iklim', 'Mitigasi dan Adaptasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 1: Dinamika Rotasi', 'Gerak Rotasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 1: Dinamika Rotasi', 'Torsi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 1: Dinamika Rotasi', 'Momen Inersia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 1: Dinamika Rotasi', 'Kesetimbangan Benda Tegar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 2: Hukum Kekekalan Energi Mekanik', 'Energi Potensial dan Kinetik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 2: Hukum Kekekalan Energi Mekanik', 'Usaha dan Perubahan Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 2: Hukum Kekekalan Energi Mekanik', 'Penerapan Hukum Kekekalan Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 3: Getaran Harmonik Sederhana', 'Konsep Osilasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 3: Getaran Harmonik Sederhana', 'Frekuensi, Amplitudo, Periode'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 3: Getaran Harmonik Sederhana', 'Getaran pada Pegas dan Bandul'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 4: Gelombang Mekanik', 'Jenis Gelombang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 4: Gelombang Mekanik', 'Sifat Gelombang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 4: Gelombang Mekanik', 'Aplikasi Gelombang Mekanik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 5: Cahaya dan Optik', 'Sifat-Sifat Cahaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 5: Cahaya dan Optik', 'Pemantulan dan Pembiasan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 5: Cahaya dan Optik', 'Alat Optik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 6: Pengukuran dalam Kerja Ilmiah', 'Besaran Pokok dan Turunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 6: Pengukuran dalam Kerja Ilmiah', 'Alat Ukur dan Ketelitian'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 6: Pengukuran dalam Kerja Ilmiah', 'Kesalahan Pengukuran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 7: Struktur Atom dan Sistem Periodik', 'Model Atom Modern'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 7: Struktur Atom dan Sistem Periodik', 'Partikel Penyusun Atom'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 7: Struktur Atom dan Sistem Periodik', 'Konfigurasi Elektron'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 7: Struktur Atom dan Sistem Periodik', 'Sistem Periodik Unsur'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 8: Hukum Dasar Kimia', 'Hukum Kekekalan Massa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 8: Hukum Dasar Kimia', 'Hukum Perbandingan Tetap dan Berganda'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 8: Hukum Dasar Kimia', 'Reaksi Kimia dan Stoikiometri'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 9: Kimia Hijau', 'Prinsip-Prinsip Kimia Hijau'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 9: Kimia Hijau', 'Bahan dan Proses Ramah Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 9: Kimia Hijau', 'Dampak Kimia Konvensional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 10: Ikatan Kimia dan Bentuk Molekul', 'Jenis-Jenis Ikatan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 10: Ikatan Kimia dan Bentuk Molekul', 'Teori Domain Elektron (VSEPR)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 10: Ikatan Kimia dan Bentuk Molekul', 'Bentuk Molekul'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 11: Metabolisme dan Enzim', 'Pengertian Metabolisme'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 11: Metabolisme dan Enzim', 'Katabolisme dan Anabolisme'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 11: Metabolisme dan Enzim', 'Fungsi Enzim'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 12: Genetika dan Pewarisan Sifat', 'Struktur DNA, Gen, RNA, Kromosom'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 12: Genetika dan Pewarisan Sifat', 'Hukum Mendel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 12: Genetika dan Pewarisan Sifat', 'Pewarisan Sifat Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 13: Pembelahan Sel', 'Mitosis dan Meiosis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 13: Pembelahan Sel', 'Siklus Sel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 13: Pembelahan Sel', 'Fungsi Pembelahan Sel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 14: Mutasi dan Evolusi', 'Mutasi Genetik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 14: Mutasi dan Evolusi', 'Teori Evolusi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 14: Mutasi dan Evolusi', 'Variasi, Seleksi, Spesiasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 15: Bioteknologi', 'Bioteknologi Konvensional dan Modern'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 15: Bioteknologi', 'Aplikasi Bioteknologi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 15: Bioteknologi', 'Dampak Sosial dan Etika'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 16: Isu Global dan Ekologi', 'Keanekaragaman Hayati'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 16: Isu Global dan Ekologi', 'Energi Terbarukan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 10 (SMA)', 'Semester 2', 'Bab 16: Isu Global dan Ekologi', 'Perubahan Iklim');

-- Grade 11
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 1: Menjelajah Sel', 'Sejarah Penemuan Sel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 1: Menjelajah Sel', 'Struktur Sel Prokariotik dan Eukariotik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 1: Menjelajah Sel', 'Fungsi Organel Sel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 1: Menjelajah Sel', 'Perbedaan Sel Hewan dan Tumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 2: Pergerakan Zat melalui Membran Sel', 'Struktur Membran Sel'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 2: Pergerakan Zat melalui Membran Sel', 'Difusi dan Osmosis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 2: Pergerakan Zat melalui Membran Sel', 'Transpor Aktif dan Pasif'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 3: Sistem Pertahanan Tubuh', 'Pertahanan Tubuh Non-Spesifik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 3: Sistem Pertahanan Tubuh', 'Imunitas Spesifik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 3: Sistem Pertahanan Tubuh', 'Sistem Kekebalan Aktif dan Pasif'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 3: Sistem Pertahanan Tubuh', 'Gangguan Sistem Imun'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 4: Mobilitas pada Manusia', 'Sistem Rangka'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 4: Mobilitas pada Manusia', 'Jenis Otot'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 4: Mobilitas pada Manusia', 'Sendi dan Mekanisme Gerak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 4: Mobilitas pada Manusia', 'Gangguan Sistem Gerak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 5: Dinamika Gerak Partikel', 'Gaya dan Gerak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 5: Dinamika Gerak Partikel', 'Hukum Newton'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 5: Dinamika Gerak Partikel', 'Gaya Gesek dan Tegangan Tali'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 5: Dinamika Gerak Partikel', 'Aplikasi Hukum Newton'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 6: Fluida Statis dan Dinamis', 'Tekanan Hidrostatik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 6: Fluida Statis dan Dinamis', 'Hukum Pascal dan Archimedes'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 6: Fluida Statis dan Dinamis', 'Fluida Dinamis dan Hukum Bernoulli'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 6: Fluida Statis dan Dinamis', 'Aplikasi Fluida'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 7: Gelombang, Bunyi, dan Cahaya', 'Konsep Dasar Gelombang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 7: Gelombang, Bunyi, dan Cahaya', 'Jenis Gelombang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 7: Gelombang, Bunyi, dan Cahaya', 'Sifat-Sifat Gelombang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 7: Gelombang, Bunyi, dan Cahaya', 'Gelombang Bunyi dan Cahaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 8: Kalor dan Termodinamika', 'Kalor dan Perubahan Suhu'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 8: Kalor dan Termodinamika', 'Perubahan Wujud'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 8: Kalor dan Termodinamika', 'Hukum Termodinamika'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 8: Kalor dan Termodinamika', 'Efisiensi Mesin Kalor'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 9: Struktur Atom', 'Teori Perkembangan Model Atom'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 9: Struktur Atom', 'Partikel Penyusun Atom'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 9: Struktur Atom', 'Nomor Atom, Massa, Isotop'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 9: Struktur Atom', 'Konfigurasi Elektron'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 10: Ikatan Kimia', 'Ikatan Ionik, Kovalen, Logam'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 10: Ikatan Kimia', 'Notasi Lewis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 10: Ikatan Kimia', 'Bentuk Molekul'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 10: Ikatan Kimia', 'Polaritas Senyawa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 11: Stoikiometri', 'Konsep Mol'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 11: Stoikiometri', 'Persamaan Reaksi Kimia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 11: Stoikiometri', 'Perhitungan Reaktan dan Produk'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 11: Stoikiometri', 'Hasil Teoritis vs Hasil Nyata'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 12: Larutan dan Sifat Koligatif', 'Jenis Larutan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 12: Larutan dan Sifat Koligatif', 'Tekanan Uap, Titik Didih, Titik Beku'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 12: Larutan dan Sifat Koligatif', 'Osmosis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam (IPA)', 'Grade 11 (SMA)', 'Semester 1', 'Bab 12: Larutan dan Sifat Koligatif', 'Aplikasi Sifat Koligatif');
