-- Seeding script for IPAS curriculum

-- Clear existing data for this subject to avoid duplicates
DELETE FROM public.curriculum WHERE subject = 'Ilmu Pengetahuan Alam dan Sosial (IPAS)';

-- Grade 3
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Bagian-bagian tumbuhan dan fungsinya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Proses fotosintesis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Siklus hidup tumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Faktor yang memengaruhi pertumbuhan tumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Siklus hidup hewan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Metamorfosis sempurna'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Metamorfosis tidak sempurna'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Pertumbuhan dan Perkembangan Makhluk Hidup', 'Hewan dengan siklus hidup tanpa metamorfosis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 2: Lingkungan dan Manfaatnya', 'Komponen Ekosistem'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 2: Lingkungan dan Manfaatnya', 'Manfaat Lingkungan bagi Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 2: Lingkungan dan Manfaatnya', 'Hubungan antar makhluk hidup'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 2: Lingkungan dan Manfaatnya', 'Rantai makanan dan jaring-jaring makanan sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 3: Wujud Zat dan Perubahannya', 'Benda Padat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 3: Wujud Zat dan Perubahannya', 'Benda Cair'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 3: Wujud Zat dan Perubahannya', 'Benda Gas'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 3: Wujud Zat dan Perubahannya', 'Perubahan Wujud Benda'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 4: Keanekaragaman Makhluk Hidup', 'Hewan di Sekitar Kita'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 4: Keanekaragaman Makhluk Hidup', 'Pengelompokan hewan berdasarkan tulang belakang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 4: Keanekaragaman Makhluk Hidup', 'Tempat hidup hewan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 4: Keanekaragaman Makhluk Hidup', 'Ciri khas hewan dan cara adaptasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 5: Pengenalan Ruang dan Denah', 'Peran Denah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 5: Pengenalan Ruang dan Denah', 'Simbol-simbol dalam denah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 1', 'BAB 5: Pengenalan Ruang dan Denah', 'Membuat denah sederhana ruangan/rumah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 1: Keanekaragaman Makhluk Hidup', 'Jenis-jenis hewan berdasarkan habitat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 1: Keanekaragaman Makhluk Hidup', 'Ciri-ciri fisik hewan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 1: Keanekaragaman Makhluk Hidup', 'Pengelompokan hewan berdasarkan makanannya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 1: Keanekaragaman Makhluk Hidup', 'Cara hewan beradaptasi dengan lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 1: Keanekaragaman Makhluk Hidup', 'Pentingnya keanekaragaman hewan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 1: Keanekaragaman Makhluk Hidup', 'Siklus Hidup Makhluk Hidup'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 2: Hubungan Makhluk Hidup dengan Lingkungan', 'Hidup Bersama Alam'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 2: Hubungan Makhluk Hidup dengan Lingkungan', 'Manusia dan Lingkungannya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 3: Energi dan Perubahannya', 'Macam-Macam Sumber Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 3: Energi dan Perubahannya', 'Perubahan Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 4: Gerak Benda di Sekitar Kita', 'Jenis Gerak Benda'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 4: Gerak Benda di Sekitar Kita', 'Faktor yang Mempengaruhi Gerak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 5: Sumber Daya Alam', 'Jenis-Jenis Sumber Daya Alam'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 5: Sumber Daya Alam', 'Pemanfaatan dan Pelestarian SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 6: Cuaca dan Kehidupan', 'Jenis-Jenis Cuaca'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 6: Cuaca dan Kehidupan', 'Pengaruh Cuaca terhadap Kehidupan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 7: Kegiatan Ekonomi di Sekitar Kita', 'Jenis-Jenis Kegiatan Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 3 (SD)', 'Semester 2', 'BAB 7: Kegiatan Ekonomi di Sekitar Kita', 'Peran Masyarakat dalam Kegiatan Ekonomi');

-- Grade 4
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 1: Tumbuhan, Sumber Kehidupan di Bumi', 'Bagian-Bagian Tumbuhan dan Fungsinya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 1: Tumbuhan, Sumber Kehidupan di Bumi', 'Proses Fotosintesis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 1: Tumbuhan, Sumber Kehidupan di Bumi', 'Siklus Hidup Tumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 1: Tumbuhan, Sumber Kehidupan di Bumi', 'Jenis Akar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 2: Wujud Zat dan Perubahannya', 'Wujud Zat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 2: Wujud Zat dan Perubahannya', 'Perubahan Wujud Zat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 2: Wujud Zat dan Perubahannya', 'Perubahan Fisika dan Kimia (pengantar dasar)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 3: Gaya di Sekitar Kita', 'Jenis-Jenis Gaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 3: Gaya di Sekitar Kita', 'Pengaruh Gaya terhadap Benda'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 3: Gaya di Sekitar Kita', 'Penerapan Gaya dalam Kehidupan Sehari-hari'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 4: Mengubah Bentuk Energi', 'Macam-Macam Bentuk Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 4: Mengubah Bentuk Energi', 'Perubahan Bentuk Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 4: Mengubah Bentuk Energi', 'Sumber Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 5: Cerita tentang Daerahku', 'Kenampakan Alam'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 5: Cerita tentang Daerahku', 'Kenampakan Sosial dan Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 1', 'BAB 5: Cerita tentang Daerahku', 'Peristiwa Alam di Daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 5: Cerita Tentang Daerahku', 'Mengenal Daerah Tempat Tinggal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 5: Cerita Tentang Daerahku', 'Potensi Alam Daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 5: Cerita Tentang Daerahku', 'Potensi Sosial Budaya Daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 5: Cerita Tentang Daerahku', 'Keunikan Daerahku'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 6: Indonesiaku Kaya Budaya', 'Keberagaman Suku Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 6: Indonesiaku Kaya Budaya', 'Bahasa Daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 6: Indonesiaku Kaya Budaya', 'Adat Istiadat dan Tradisi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 6: Indonesiaku Kaya Budaya', 'Kesenian Tradisional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 6: Indonesiaku Kaya Budaya', 'Semangat Persatuan dalam Keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 7: Bagaimana Mendapatkan Semua Keperluan Kita?', 'Kebutuhan Dasar Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 7: Bagaimana Mendapatkan Semua Keperluan Kita?', 'Cara Memenuhi Kebutuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 7: Bagaimana Mendapatkan Semua Keperluan Kita?', 'Sistem Ekonomi Sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 7: Bagaimana Mendapatkan Semua Keperluan Kita?', 'Sumber Daya dan Pemanfaatannya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 8: Membangun Masyarakat yang Beradab', 'Hidup Bermasyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 8: Membangun Masyarakat yang Beradab', 'Nilai-Nilai Sosial dan Moral'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 8: Membangun Masyarakat yang Beradab', 'Etika dan Tata Krama'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 8: Membangun Masyarakat yang Beradab', 'Kewajiban dan Hak Warga'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 4 (SD)', 'Semester 2', 'BAB 8: Membangun Masyarakat yang Beradab', 'Peran Aktif dalam Masyarakat');

-- Grade 5
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 1: Melihat Karena Cahaya, Mendengar Karena Bunyi', 'Cahaya dan Sifat-Sifatnya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 1: Melihat Karena Cahaya, Mendengar Karena Bunyi', 'Melihat karena Cahaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 1: Melihat Karena Cahaya, Mendengar Karena Bunyi', 'Bunyi dan Sifat-Sifatnya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 1: Melihat Karena Cahaya, Mendengar Karena Bunyi', 'Mendengar karena Bunyi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 2: Harmoni dalam Ekosistem', 'Ekosistem dan Komponennya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 2: Harmoni dalam Ekosistem', 'Rantai Makanan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 2: Harmoni dalam Ekosistem', 'Jaring-Jaring Makanan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 2: Harmoni dalam Ekosistem', 'Peran Manusia dalam Ekosistem'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 3: Magnet, Listrik, dan Teknologi untuk Kehidupan', 'Magnet dan Sifat-Sifatnya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 3: Magnet, Listrik, dan Teknologi untuk Kehidupan', 'Listrik dan Rangkaian Listrik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 3: Magnet, Listrik, dan Teknologi untuk Kehidupan', 'Teknologi Berbasis Listrik dan Magnet'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 4: Ayo Berkenalan dengan Bumi Kita', 'Bumi dalam Tata Surya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 4: Ayo Berkenalan dengan Bumi Kita', 'Perputaran Bumi (Rotasi)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 4: Ayo Berkenalan dengan Bumi Kita', 'Pergerakan Bumi Mengelilingi Matahari (Revolusi)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 4: Ayo Berkenalan dengan Bumi Kita', 'Peristiwa Alam di Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 5: Bagaimana Kita Hidup dan Bertumbuh', 'Pertumbuhan dan Perkembangan Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 5: Bagaimana Kita Hidup dan Bertumbuh', 'Perubahan Fisik dan Psikologis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 5: Bagaimana Kita Hidup dan Bertumbuh', 'Kebutuhan Dasar Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 5: Bagaimana Kita Hidup dan Bertumbuh', 'Menjaga Kesehatan Tubuh'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 6: Indonesiaku Kaya Raya', 'Kekayaan Alam Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 6: Indonesiaku Kaya Raya', 'Keragaman Budaya Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 1', 'BAB 6: Indonesiaku Kaya Raya', 'Peran Masyarakat dalam Melestarikan Lingkungan dan Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 1: Gaya dan Pesawat Sederhana', 'Jenis-Jenis Gaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 1: Gaya dan Pesawat Sederhana', 'Pesawat Sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 2: Cahaya dan Pemanfaatannya', 'Sifat-Sifat Cahaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 2: Cahaya dan Pemanfaatannya', 'Pemanfaatan Cahaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 3: Bumi dan Alam Semesta', 'Struktur dan Lapisan Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 3: Bumi dan Alam Semesta', 'Bumi dalam Tata Surya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 3: Bumi dan Alam Semesta', 'Peristiwa Alam'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 4: Ekosistem dan Interaksi Makhluk Hidup', 'Komponen Ekosistem'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 4: Ekosistem dan Interaksi Makhluk Hidup', 'Jenis-Jenis Ekosistem'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 4: Ekosistem dan Interaksi Makhluk Hidup', 'Rantai Makanan dan Jaring-Jaring Makanan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 5: Manusia dan Pertumbuhannya', 'Pertumbuhan dan Perkembangan Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 5: Manusia dan Pertumbuhannya', 'Kesehatan dan Kebersihan Diri'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 6: Kekayaan dan Kebanggaan Daerah', 'Keunikan Daerah Tempat Tinggal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 6: Kekayaan dan Kebanggaan Daerah', 'Sumber Daya Alam Daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 6: Kekayaan dan Kebanggaan Daerah', 'Pelestarian Lingkungan dan Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 7: Perubahan Kondisi Alam dan Pengaruhnya', 'Penyebab Perubahan Kondisi Alam'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 7: Perubahan Kondisi Alam dan Pengaruhnya', 'Dampak Perubahan terhadap Kehidupan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 5 (SD)', 'Semester 2', 'BAB 7: Perubahan Kondisi Alam dan Pengaruhnya', 'Mitigasi dan Adaptasi');

-- Grade 6
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 1: Bagaimana Tubuh Kita Bergerak', 'Sistem Gerak pada Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 1: Bagaimana Tubuh Kita Bergerak', 'Sistem Saraf dan Koordinasi Gerak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 1: Bagaimana Tubuh Kita Bergerak', 'Gangguan dan Penyakit pada Sistem Gerak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 2: Makhluk Hidup dan Lingkungannya', 'Ciri Khusus Makhluk Hidup'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 2: Makhluk Hidup dan Lingkungannya', 'Perkembangbiakan Makhluk Hidup'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 3: Perkembangan Kehidupan Manusia', 'Tahapan Pertumbuhan dan Perkembangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 3: Perkembangan Kehidupan Manusia', 'Masa Pubertas'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 4: Kehidupan Sosial dan Globalisasi', 'Interaksi Antarnegara'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 4: Kehidupan Sosial dan Globalisasi', 'Globalisasi dan Pengaruhnya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 5: Bumi dan Antariksa', 'Kenampakan Alam di Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 5: Bumi dan Antariksa', 'Pengenalan Antariksa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 6: Proyek IPAS', 'Proyek Ilmiah Sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 1', 'BAB 6: Proyek IPAS', 'Proyek Sosial dan Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 4: Indonesia dan Masyarakat Dunia', 'Hubungan Antarnegara'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 4: Indonesia dan Masyarakat Dunia', 'Masyarakat Dunia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 4: Indonesia dan Masyarakat Dunia', 'Perubahan Sosial Budaya di Era Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 5: Bumi dan Antariksa', 'Mengenal Bumi, Matahari, dan Bulan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 5: Bumi dan Antariksa', 'Gerak Rotasi dan Revolusi Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 5: Bumi dan Antariksa', 'Sistem Tata Surya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 5: Bumi dan Antariksa', 'Peristiwa Alam Akibat Interaksi Bumi dan Benda Langit'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 6: Benarkah Energi di Bumi Akan Habis?', 'Apa Jadinya Jika Tidak Ada Energi?'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 6: Benarkah Energi di Bumi Akan Habis?', 'Bentuk dan Sumber Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 6: Benarkah Energi di Bumi Akan Habis?', 'Hukum Kekekalan Energi dan Perubahan Bentuk Energi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 6: Benarkah Energi di Bumi Akan Habis?', 'Benarkah Energi Akan Habis?'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 6: Benarkah Energi di Bumi Akan Habis?', 'Energi Terbarukan dan Teknologi Ramah Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 7: Bumi Kita Terancam Bahaya', 'Ancaman terhadap Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 7: Bumi Kita Terancam Bahaya', 'Bencana Alam dan Penanggulangannya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 7: Bumi Kita Terancam Bahaya', 'Tanggung Jawab Bersama dalam Menjaga Bumi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 8: Proyek Akhir IPAS', 'Proyek Ilmiah dan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Alam dan Sosial (IPAS)', 'Grade 6 (SD)', 'Semester 2', 'BAB 8: Proyek Akhir IPAS', 'Presentasi Proyek');
