-- Seeding script for Matematika curriculum

-- Clear existing data for this subject to avoid duplicates
DELETE FROM public.curriculum WHERE subject = 'Matematika';

-- Grade 1
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 1: Bilangan dan Operasi Hitung', 'Bilangan 1–10'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 1: Bilangan dan Operasi Hitung', 'Mengurutkan Bilangan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 1: Bilangan dan Operasi Hitung', 'Membandingkan Bilangan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 1: Bilangan dan Operasi Hitung', 'Penjumlahan (hingga 10)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 1: Bilangan dan Operasi Hitung', 'Pengurangan (hingga 10)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 1: Bilangan dan Operasi Hitung', 'Nilai Tempat (satuan dan puluhan)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 2: Pengukuran', 'Konsep Waktu (hari, jam)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 2: Pengukuran', 'Panjang dengan satuan tidak baku (jengkal, hasta)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 3: Bangun Datar', 'Mengenal bentuk persegi, segitiga, lingkaran'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 4: Pola Bilangan', 'Pola berulang sederhana (gambar/benda)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 1', 'BAB 5: Analisis Data Sederhana', 'Mengelompokkan benda berdasarkan atribut'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 1: Membilang dan Berhitung', 'Bilangan sampai 20'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 1: Membilang dan Berhitung', 'Hitung maju dan mundur'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 1: Membilang dan Berhitung', 'Nilai tempat'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 1: Membilang dan Berhitung', 'Membandingkan bilangan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 2: Operasi Hitung', 'Penjumlahan & pengurangan (hingga 20)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 2: Operasi Hitung', 'Konsep "lebih dari", "kurang dari", "selisih"'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 2: Operasi Hitung', 'Soal cerita'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 3: Pengukuran', 'Mengukur panjang (satuan tidak baku)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 3: Pengukuran', 'Konsep waktu (jam dan hari)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 4: Bangun Datar', 'Mengenal berbagai bentuk bangun datar'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 1 (SD)', 'Semester 2', 'BAB 5: Diagram', 'Membaca diagram sederhana');

-- Grade 2
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 1', 'BAB 1: Bilangan', 'Bilangan cacah sampai 1000'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 1', 'BAB 1: Bilangan', 'Nilai tempat: satuan, puluhan, ratusan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 1', 'BAB 1: Bilangan', 'Perbandingan bilangan (> , < , =)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 1', 'BAB 2: Operasi Hitung', 'Penjumlahan & pengurangan hingga 1000'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 1', 'BAB 2: Operasi Hitung', 'Hubungan antara penjumlahan dan pengurangan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 1', 'BAB 3: Pengukuran', 'Panjang (cm, m)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 1', 'BAB 3: Pengukuran', 'Waktu (jam, menit), durasi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 1', 'BAB 4: Data', 'Membaca tabel dan grafik sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 1', 'BAB 4: Data', 'Menafsirkan informasi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 1: Bilangan', 'Membaca, menulis, mengurutkan bilangan hingga 1000'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 1: Bilangan', 'Nilai tempat'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 1: Bilangan', 'Penjumlahan & pengurangan (hingga 1000)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 2: Pengukuran', 'Panjang (cm, m)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 2: Pengukuran', 'Berat (kg, gram)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 2: Pengukuran', 'Waktu dan durasi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 3: Perkalian dan Pembagian', 'Konsep perkalian sebagai penjumlahan berulang'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 3: Perkalian dan Pembagian', 'Perkalian dasar (2, 5, 10)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 3: Perkalian dan Pembagian', 'Konsep pembagian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 3: Perkalian dan Pembagian', 'Soal cerita'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 4: Bangun Datar', 'Bentuk bangun datar'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 4: Bangun Datar', 'Sifat-sifat bangun'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 4: Bangun Datar', 'Menggambar bentuk'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 5: Pecahan', 'Konsep pecahan sederhana (½, ¼)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 5: Pecahan', 'Bagian dari benda'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 6: Data', 'Membaca tabel/grafik sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 2 (SD)', 'Semester 2', 'BAB 6: Data', 'Mengumpulkan & menyajikan data');

-- Grade 3
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Bilangan', 'Bilangan cacah hingga 1000'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Bilangan', 'Nilai tempat'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Bilangan', 'Urutan dan perbandingan bilangan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 1: Bilangan', 'Letak pada garis bilangan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 2: Operasi Hitung', 'Penjumlahan dan pengurangan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 2: Operasi Hitung', 'Perkalian (konsep dan soal cerita)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 2: Operasi Hitung', 'Pembagian (konsep dasar)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 3: Pengukuran', 'Panjang, berat, waktu'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 4: Geometri', 'Bangun datar (identifikasi dan unsur)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 4: Geometri', 'Pengenalan bangun ruang'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 5: Pecahan', 'Pengenalan pecahan sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 6: Soal Cerita', 'Penerapan penjumlahan, pengurangan, perkalian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 7: Uang', 'Mengenal pecahan uang dan penggunaannya'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 8: Garis Bilangan', 'Letak bilangan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 1', 'BAB 9: Diagram Garis', 'Membaca diagram garis sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 2', 'BAB 1: Pecahan', 'Membandingkan pecahan sederhana'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 2', 'BAB 2: Bangun Datar', 'Mengenal bentuk, sisi, dan sudut'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 2', 'BAB 3: Keliling dan Luas', 'Menghitung keliling dan luas persegi & persegi panjang'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 3 (SD)', 'Semester 2', 'BAB 4: Penyajian Data', 'Menyajikan, mengurutkan, membandingkan data dalam tabel');

-- Grade 4
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '1. Bilangan', 'Bilangan Cacah: Membaca, menulis, nilai tempat, membandingkan, mengurutkan, komposisi, dan dekomposisi hingga 10.000.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '1. Bilangan', 'Bilangan Bulat: Pengenalan bilangan bulat positif dan negatif.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '1. Bilangan', 'Pecahan: Pecahan sederhana, pecahan dengan pembilang satu, penyebut sama, pecahan senilai, pecahan desimal (persepuluhan dan perseratusan).'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '1. Bilangan', 'Operasi Hitung Bilangan Cacah: Penjumlahan, pengurangan, perkalian, pembagian, dan soal cerita.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '2. Pengukuran dan Geometri', 'Pengukuran: Waktu, panjang, berat, volume.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '2. Pengukuran dan Geometri', 'Geometri: Bentuk segitiga, persegi, persegi panjang, lingkaran, balok, dan kubus.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '2. Pengukuran dan Geometri', 'Sudut: Pengenalan macam-macam sudut.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '2. Pengukuran dan Geometri', 'Diagram Garis: Membaca dan membuat diagram garis.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '3. Data', 'Penyusunan Data: Pengumpulan, pengolahan, penyajian dalam bentuk tabel dan diagram.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '4. Faktor dan Kelipatan', 'Konsep Faktor dan Kelipatan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 1', '5. Mata Uang', 'Mengenal Nilai Mata Uang Rupiah'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '1. Bilangan dan Operasi Hitung', 'Bilangan Desimal: Membaca, menulis, operasi hitung desimal.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '1. Bilangan dan Operasi Hitung', 'Pecahan: Operasi hitung (penjumlahan, pengurangan, perkalian, pembagian), jenis-jenis pecahan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '1. Bilangan dan Operasi Hitung', 'Operasi Hitung Campuran: Bilangan bulat dan soal cerita.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '2. Pengukuran', 'Konversi Satuan: Panjang, berat, luas, volume.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '2. Pengukuran', 'Luas: Menghitung luas persegi, persegi panjang, segitiga, dll.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '2. Pengukuran', 'Volume: Menghitung volume kubus dan balok.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '3. Geometri', 'Bangun Datar: Jenis, sifat, keliling, dan luas.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '3. Geometri', 'Bangun Ruang: Kubus dan balok (sifat, volume, luas permukaan).'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '4. Data dan Statistik', 'Penyajian Data: Tabel, diagram, grafik.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '4. Data dan Statistik', 'Interpretasi Data: Menafsirkan dan mengambil kesimpulan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '5. Kalimat Matematika dan Perhitungan', 'Kalimat Matematika: Menyusun dari soal cerita.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 4 (SD)', 'Semester 2', '5. Kalimat Matematika dan Perhitungan', 'Strategi Berhitung: Estimasi, kalkulasi mental.');

-- Grade 5
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '1. Bilangan dan Operasi Hitung', 'Bilangan Cacah hingga 100.000: Nilai tempat, membaca, menulis, urutan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '1. Bilangan dan Operasi Hitung', 'KPK dan FPB: Konsep, penerapan dalam soal.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '1. Bilangan dan Operasi Hitung', 'Bilangan Pecahan: Operasi hitung (penjumlahan, pengurangan).'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '1. Bilangan dan Operasi Hitung', 'Bilangan Desimal: Operasi hitung lengkap.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '2. Geometri', 'Keliling: Persegi, persegi panjang, segitiga.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '2. Geometri', 'Luas: Persegi, persegi panjang, segitiga, gabungan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '2. Geometri', 'Sudut: Jenis-jenis sudut.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '2. Geometri', 'Volume: Kubus dan balok.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '3. Pengukuran', 'Konversi Satuan: Panjang, berat, waktu.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '4. Data', 'Pengumpulan Data'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 1', '4. Data', 'Piktogram dan Diagram Batang'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '1. Pecahan', 'Penjumlahan, pengurangan, perkalian, pembagian.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '2. Bangun Datar', 'Luas jajar genjang, segitiga, perbandingan sifat.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '3. Perbandingan', 'Konsep dasar perbandingan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '4. Bangun Ruang', 'Pengenalan dan volume bangun ruang.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '5. Rasio dan Diagram', 'Konsep rasio, membaca dan membuat diagram.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '6. Bilangan', 'Bilangan desimal dan bilangan bulat.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '7. Pengukuran', 'Waktu (termasuk notasi 24 jam).'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '8. Sudut', 'Jenis sudut (siku-siku, lancip, tumpul).'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '9. Data', 'Penyajian dan pengolahan data (diagram).'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '10. Kekongruenan dan Sudut', 'Kekongruenan bangun, hubungan sudut.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 5 (SD)', 'Semester 2', '11. Faktor dan Kelipatan', 'Pengulangan dan penerapan lanjutan.');

-- Grade 6
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '1. Bilangan dan Aljabar', 'Pecahan: Perkalian, pembagian, konversi.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '1. Bilangan dan Aljabar', 'Desimal: Perbandingan, konversi.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '1. Bilangan dan Aljabar', 'Bilangan Bulat: Operasi hitung dan soal cerita.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '1. Bilangan dan Aljabar', 'Rasio: Konsep dan penerapan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '2. Geometri', 'Bangun Ruang: Kubus dan balok.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '2. Geometri', 'Luas Bangun Datar: Persegi, persegi panjang, segitiga, lingkaran.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '2. Geometri', 'Volume: Kubus dan balok.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '3. Statistika dan Peluang', 'Peluang: Konsep dasar peluang dan contoh permainan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '3. Statistika dan Peluang', 'Diagram: Membaca dan membuat.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '4. Operasi Hitung', 'Operasi campuran bilangan bulat dan pecahan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '4. Operasi Hitung', 'Kelipatan dan perbandingan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '5. Simetri', 'Konsep dasar simetri.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 1', '6. Skala dan Perbandingan', 'Penggunaan skala dan perbandingan dalam peta/konteks nyata.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '1. Bilangan dan Operasi Hitung', 'Bilangan Bulat, Pecahan, Desimal: Operasi hitung lengkap dan konversi.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '1. Bilangan dan Operasi Hitung', 'Operasi Hitung Campuran'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '2. Bangun Datar dan Ruang', 'Luas dan Keliling: Persegi, persegi panjang, segitiga, jajar genjang, lingkaran.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '2. Bangun Datar dan Ruang', 'Bangun Ruang: Kubus, balok, prisma, tabung, limas.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '3. Perbandingan', 'Perhitungan dan aplikasi perbandingan.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '4. Penyajian Data', 'Diagram batang, lingkaran, garis, tabel frekuensi, piktogram.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '4. Penyajian Data', 'Analisis data dari diagram.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '5. Peluang', 'Menghitung dan membandingkan peluang kejadian.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '6. Geometri', 'Perbandingan sifat bangun.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '6. Geometri', 'Lokasi pada peta dengan sistem berpetak.'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 6 (SD)', 'Semester 2', '7. Aljabar', 'Konsep dasar aljabar.');

-- Grade 7
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 1: Bilangan', 'Bilangan bulat (positif, negatif, dan nol)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 1: Bilangan', 'Bilangan pecahan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 1: Bilangan', 'Operasi hitung bilangan bulat dan pecahan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 2: Himpunan', 'Konsep himpunan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 2: Himpunan', 'Notasi himpunan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 2: Himpunan', 'Operasi pada himpunan (irisan, gabungan, selisih)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 3: Bentuk Aljabar', 'Konsep variabel dan konstanta'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 3: Bentuk Aljabar', 'Operasi hitung bentuk aljabar (penjumlahan, pengurangan, perkalian, pembagian)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 4: Persamaan dan Pertidaksamaan Linear Satu Variabel', 'Penyelesaian persamaan linear satu variabel'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 4: Persamaan dan Pertidaksamaan Linear Satu Variabel', 'Penyelesaian pertidaksamaan linear satu variabel'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 5: Perbandingan', 'Perbandingan senilai'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 5: Perbandingan', 'Perbandingan berbalik nilai'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 6: Geometri', 'Garis dan sudut'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 6: Geometri', 'Bangun datar (segitiga, segi empat, lingkaran)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 7: Penyajian Data', 'Memahami berbagai cara penyajian data'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 1', 'BAB 7: Penyajian Data', 'Menginterpretasikan data'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 1: Perbandingan (lanjutan)', 'Konsep dan jenis perbandingan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 1: Perbandingan (lanjutan)', 'Penerapan dalam soal cerita'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 2: Aritmatika Sosial', 'Untung, rugi, persentase'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 2: Aritmatika Sosial', 'Bruto, neto, tara'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 2: Aritmatika Sosial', 'Bunga tunggal dan pajak'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 3: Garis dan Sudut (lanjutan)', 'Jenis-jenis garis dan sudut'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 3: Garis dan Sudut (lanjutan)', 'Hubungan antar sudut'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 3: Garis dan Sudut (lanjutan)', 'Menentukan besar sudut'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 4: Segiempat dan Segitiga', 'Jenis-jenis segiempat dan segitiga'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 4: Segiempat dan Segitiga', 'Keliling dan luas'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 4: Segiempat dan Segitiga', 'Hubungan sisi dan sudut'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 4: Segiempat dan Segitiga', 'Teorema Pythagoras'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 5: Penyajian Data (lanjutan)', 'Tabel, diagram batang, garis, lingkaran'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 5: Penyajian Data (lanjutan)', 'Membaca dan menafsirkan data'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 5: Penyajian Data (lanjutan)', 'Membuat diagram'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 6: Bilangan Bulat (penguatan)', 'Pengertian dan operasi hitung'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 7: Aljabar (penguatan)', 'Variabel, konstanta, suku, operasi aljabar'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 8: Persamaan dan Pertidaksamaan Linear Satu Variabel (penguatan)', 'Pemahaman dan penyelesaian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 9: Himpunan (penguatan)', 'Anggota dan operasi himpunan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 7 (SMP)', 'Semester 2', 'BAB 10: Relasi dan Fungsi (pengantar)', 'Konsep relasi dan fungsi');

-- Grade 8
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 1: Pola Bilangan', 'Jenis-jenis pola (ganjil, genap, persegi, segitiga, Fibonacci)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 2: Koordinat Kartesius', 'Sistem koordinat dan posisi titik'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 3: Relasi dan Fungsi', 'Diagram panah, tabel, grafik'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 3: Relasi dan Fungsi', 'Domain, kodomain, range'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 4: Persamaan Garis Lurus', 'Konsep persamaan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 4: Persamaan Garis Lurus', 'Grafik, gradien, titik potong'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 5: Sistem Persamaan Linear Dua Variabel', 'Konsep dan penyelesaian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 6: Bilangan Berpangkat (Eksponen)', 'Sifat dan operasi eksponen'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 7: Teorema Pythagoras', 'Penerapan pada segitiga siku-siku'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 1', 'BAB 8: Persamaan dan Pertidaksamaan Linear Satu Variabel (penguatan)', 'Penyelesaian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 2', 'BAB 1: Relasi dan Fungsi (lanjutan)', 'Penyajian relasi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 2', 'BAB 1: Relasi dan Fungsi (lanjutan)', 'Domain, kodomain, range'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 2', 'BAB 1: Relasi dan Fungsi (lanjutan)', 'Grafik dan rumus fungsi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 2', 'BAB 2: Persamaan Garis Lurus (lanjutan)', 'Menggambar grafik'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 2', 'BAB 2: Persamaan Garis Lurus (lanjutan)', 'Gradien dan penyelesaian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 2', 'BAB 3: Statistika', 'Mengumpulkan dan menyajikan data'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 2', 'BAB 3: Statistika', 'Mean, median, modus'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 8 (SMP)', 'Semester 2', 'BAB 4: Korespondensi Satu-satu', 'Hubungan antara dua himpunan');

-- Grade 9
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 1', 'BAB 1: Sistem Persamaan Linear Dua Variabel (penguatan)', 'Konsep, penyelesaian, dan pemodelan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 1', 'BAB 2: Bangun Ruang Sisi Datar', 'Jenis bangun (kubus, balok, prisma, limas)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 1', 'BAB 2: Bangun Ruang Sisi Datar', 'Jaring-jaring'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 1', 'BAB 2: Bangun Ruang Sisi Datar', 'Luas permukaan dan volume'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 1', 'BAB 2: Bangun Ruang Sisi Datar', 'Penyelesaian masalah kontekstual'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 1', 'BAB 3: Perpangkatan dan Bentuk Akar', 'Definisi dan sifat-sifat'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 1', 'BAB 4: Persamaan dan Fungsi Kuadrat', 'Konsep, grafik, dan penyelesaian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 1', 'BAB 5: Transformasi Geometri', 'Translasi, refleksi, rotasi, dilatasi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 1', 'BAB 6: Bangun Ruang Sisi Lengkung (pengantar)', 'Tabung, kerucut, bola'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 2', 'BAB 1: Bangun Ruang Sisi Lengkung (lanjutan)', 'Luas permukaan dan volume tabung, kerucut, bola'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 2', 'BAB 2: Transformasi Geometri (lanjutan)', 'Pergeseran dan rotasi titik/garis/bidang'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 2', 'BAB 3: Peluang', 'Konsep dasar dan menghitung peluang'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 2', 'BAB 4: Kesebangunan dan Kekongruenan', 'Konsep dan penerapan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 9 (SMP)', 'Semester 2', 'BAB 5: Soal Cerita', 'Penerapan berbagai konsep matematika dalam kehidupan sehari-hari');

-- Grade 10
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 1: Eksponen dan Logaritma', 'Definisi eksponen (perpangkatan)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 1: Eksponen dan Logaritma', 'Sifat-sifat eksponen (perkalian, pembagian, pangkat nol, dll.)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 1: Eksponen dan Logaritma', 'Fungsi eksponen (pertumbuhan dan peluruhan)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 1: Eksponen dan Logaritma', 'Definisi logaritma (invers dari eksponen)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 1: Eksponen dan Logaritma', 'Sifat-sifat logaritma'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 1: Eksponen dan Logaritma', 'Penerapan logaritma dalam menyelesaikan persamaan eksponensial'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 2: Barisan dan Deret', 'Barisan aritmetika (dengan beda tetap)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 2: Barisan dan Deret', 'Barisan geometri (dengan rasio tetap)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 2: Barisan dan Deret', 'Deret aritmetika (penjumlahan suku-suku barisan aritmetika)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 2: Barisan dan Deret', 'Deret geometri (penjumlahan suku-suku barisan geometri)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 3: Sistem Persamaan dan Pertidaksamaan Linear', 'Sistem Persamaan Linear Dua Variabel (SPLDV)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 3: Sistem Persamaan dan Pertidaksamaan Linear', 'Sistem Persamaan Linear Tiga Variabel (SPLTV)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 3: Sistem Persamaan dan Pertidaksamaan Linear', 'Sistem Pertidaksamaan Linear Dua Variabel (SPtLDV)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 4: Fungsi Kuadrat', 'Definisi fungsi kuadrat'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 4: Fungsi Kuadrat', 'Grafik fungsi kuadrat (parabola)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 4: Fungsi Kuadrat', 'Aplikasi fungsi kuadrat dalam pemodelan masalah'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 5: Trigonometri', 'Pengenalan fungsi trigonometri'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 5: Trigonometri', 'Identitas trigonometri'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 5: Trigonometri', 'Aplikasi dalam segitiga'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 6: Vektor', 'Pengenalan konsep vektor'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 6: Vektor', 'Operasi vektor'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 6: Vektor', 'Penerapan vektor dalam geometri'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 7: Statistika dan Peluang', 'Pengantar statistika (data, penyajian data, ukuran pemusatan data)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 1', 'BAB 7: Statistika dan Peluang', 'Konsep dasar peluang'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 1: Sistem Persamaan dan Pertidaksamaan Linear', 'Menyelesaikan sistem persamaan linear dua variabel dan tiga variabel'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 1: Sistem Persamaan dan Pertidaksamaan Linear', 'Menyelesaikan sistem pertidaksamaan linear dua variabel'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 2: Fungsi Kuadrat', 'Mempelajari bentuk umum f(x) = ax² + bx + c'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 2: Fungsi Kuadrat', 'Menggambar grafik fungsi kuadrat'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 2: Fungsi Kuadrat', 'Menganalisis titik potong dengan sumbu x dan sumbu y'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 2: Fungsi Kuadrat', 'Penerapan fungsi kuadrat dalam berbagai masalah'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 3: Statistika', 'Mengumpulkan data dari berbagai sumber'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 3: Statistika', 'Menyajikan data dalam bentuk tabel, diagram, dan grafik'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 3: Statistika', 'Rata-rata, median, dan modus'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 3: Statistika', 'Jangkauan, kuartil, dan simpangan baku'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 4: Peluang', 'Definisi peluang, ruang sampel, dan kejadian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 4: Peluang', 'Menghitung peluang suatu kejadian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 4: Peluang', 'Peluang komplemen'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 4: Peluang', 'Peluang dari gabungan atau irisan dua kejadian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 5: Eksponen dan Logaritma', 'Perkalian, pembagian, dan pemangkatan pada eksponen'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 5: Eksponen dan Logaritma', 'Fungsi eksponen dan grafiknya'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 5: Eksponen dan Logaritma', 'Definisi logaritma dan hubungannya dengan eksponen'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 5: Eksponen dan Logaritma', 'Sifat-sifat logaritma'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 6: Barisan dan Deret', 'Barisan aritmatika dan geometri'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 6: Barisan dan Deret', 'Deret aritmatika dan geometri'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 7: Trigonometri', 'Sinus, cosinus, dan tangen pada segitiga siku-siku'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 7: Trigonometri', 'Hubungan antara perbandingan trigonometri'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 7: Trigonometri', 'Grafik sinus, cosinus, dan tangen'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 10 (SMA)', 'Semester 2', 'BAB 7: Trigonometri', 'Penerapan dalam berbagai masalah');

-- Grade 11
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 1: Fungsi Komposisi dan Invers', 'Definisi fungsi, domain, kodomain, dan range'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 1: Fungsi Komposisi dan Invers', 'Menggabungkan dua fungsi atau lebih'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 1: Fungsi Komposisi dan Invers', 'Mencari invers suatu fungsi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 1: Fungsi Komposisi dan Invers', 'Penjumlahan, pengurangan, perkalian, dan pembagian fungsi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 2: Lingkaran', 'Konsep lingkaran, busur, dan unsur-unsur lainnya'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 2: Lingkaran', 'Hubungan antara lingkaran dan garis singgung'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 2: Lingkaran', 'Konsep tali busur dalam lingkaran'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 3: Statistika', 'Mean, median, modus untuk data tunggal maupun berkelompok'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 3: Statistika', 'Rentang, kuartil, simpangan kuartil, varians, dan standar deviasi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 3: Statistika', 'Tabel distribusi frekuensi, histogram, poligon, dan diagram batang'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 3: Statistika', 'Interpretasi dan pemaknaan hasil pengolahan data'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 4: Bilangan Kompleks', '𝑧 = 𝑎 + 𝑏𝑖, di mana 𝑖² = −1'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 4: Bilangan Kompleks', 'Penjumlahan, pengurangan, perkalian, pembagian'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 4: Bilangan Kompleks', 'Konsep konjugat kompleks dan penggunaannya'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 11 (SMA)', 'Semester 1', 'BAB 4: Bilangan Kompleks', 'Pengenalan awal bentuk polar');

-- Grade 12
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 1: Program Linear', 'Model matematika masalah optimasi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 1: Program Linear', 'Sistem pertidaksamaan linear dua variabel'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 1: Program Linear', 'Metode grafik untuk menentukan nilai optimum'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 1: Program Linear', 'Aplikasi program linear'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 2: Limit Fungsi', 'Konsep limit di titik tertentu'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 2: Limit Fungsi', 'Limit kiri dan limit kanan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 2: Limit Fungsi', 'Limit tak hingga'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 2: Limit Fungsi', 'Aplikasi dalam pendekatan nilai fungsi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 3: Turunan Fungsi', 'Konsep turunan sebagai laju perubahan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 3: Turunan Fungsi', 'Aturan turunan (fungsi aljabar, eksponen, logaritma)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 3: Turunan Fungsi', 'Turunan fungsi komposit'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 1', 'BAB 3: Turunan Fungsi', 'Penerapan turunan: kecepatan, maksimum/minimum'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 4: Integral', 'Konsep integral sebagai luas'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 4: Integral', 'Integral tak tentu dan tentu'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 4: Integral', 'Aturan integrasi'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 4: Integral', 'Aplikasi integral dalam menghitung luas daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 5: Statistika Lanjut', 'Distribusi frekuensi data kelompok'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 5: Statistika Lanjut', 'Ukuran pemusatan dan penyebaran lanjutan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 5: Statistika Lanjut', 'Penerapan statistika dalam pengambilan keputusan'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 6: Peluang Distribusi', 'Distribusi peluang diskret (misalnya binomial)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 6: Peluang Distribusi', 'Distribusi peluang kontinu (normal)'),
('Kurikulum Merdeka Belajar', 'id', 'Matematika', 'Grade 12 (SMA)', 'Semester 2', 'BAB 6: Peluang Distribusi', 'Aplikasi distribusi peluang');
