-- Seed script for Ilmu Pengetahuan Sosial (IPS) curriculum
-- Language: Indonesian
-- Curriculum Type: Kurikulum Merdeka Belajar

-- Clear existing IPS data to prevent duplicates
DELETE FROM public.curriculum WHERE subject = 'Ilmu Pengetahuan Sosial (IPS)';

-- Grade 7
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Keberadaan Diri dan Keluarga', 'Mengenal Identitas Diri'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Keberadaan Diri dan Keluarga', 'Struktur dan Peran Keluarga'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Keberadaan Diri dan Keluarga', 'Interaksi Sosial di Lingkungan Terdekat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Keberadaan Diri dan Keluarga', 'Keterlibatan Keluarga dalam Pendidikan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Keberadaan Diri dan Keluarga', 'Pengaruh Globalisasi terhadap Kehidupan Keluarga'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Keanekaragaman Lingkungan Sekitar', 'Mengenal Lingkungan Sekitar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Keanekaragaman Lingkungan Sekitar', 'Keanekaragaman Alam dan Budaya di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Keanekaragaman Lingkungan Sekitar', 'Hubungan Manusia dan Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Keanekaragaman Lingkungan Sekitar', 'Potensi Ekonomi dari Lingkungan Sekitar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Potensi Ekonomi Lingkungan', 'Kondisi Geografis dan Wilayah Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Potensi Ekonomi Lingkungan', 'Membaca Peta dan Komponen-Komponennya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Potensi Ekonomi Lingkungan', 'Aktivitas Ekonomi dalam Memenuhi Kebutuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Potensi Ekonomi Lingkungan', 'Nilai dan Norma dalam Kehidupan Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Potensi Ekonomi Lingkungan', 'Kebutuhan dan Kelangkaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Pemberdayaan Masyarakat', 'Interaksi Antarwilayah dan Antar Ruang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Pemberdayaan Masyarakat', 'Lembaga Sosial dan Fungsi Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Pemberdayaan Masyarakat', 'Dinamika Kependudukan di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Pemberdayaan Masyarakat', 'Manusia sebagai Makhluk Sosial dan Ekonomi yang Bermoral'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Pemberdayaan Masyarakat', 'Sosialisasi dan Peran Individu dalam Masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 1: Perubahan Potensi Sumber Daya Alam', 'Potensi SDA di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 1: Perubahan Potensi Sumber Daya Alam', 'Faktor Perubahan SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 1: Perubahan Potensi Sumber Daya Alam', 'Dampak Sosial dan Ekonomi Akibat Perubahan SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 2: Aktivitas Ekonomi Masa Lalu dan Sekarang', 'Aktivitas Ekonomi Masyarakat Tradisional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 2: Aktivitas Ekonomi Masa Lalu dan Sekarang', 'Aktivitas Ekonomi Masyarakat Modern'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 2: Aktivitas Ekonomi Masa Lalu dan Sekarang', 'Pelaku Ekonomi dan Peranannya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 2: Aktivitas Ekonomi Masa Lalu dan Sekarang', 'Permintaan dan Penawaran dalam Pasar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 3: Peran Masyarakat dalam Rantai Ekonomi', 'Status dan Peran Sosial dalam Masyarakat Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 3: Peran Masyarakat dalam Rantai Ekonomi', 'Diferensiasi Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 3: Peran Masyarakat dalam Rantai Ekonomi', 'Stratifikasi Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 3: Peran Masyarakat dalam Rantai Ekonomi', 'Mobilitas Sosial dan Perubahan Status Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 4: Keragaman Budaya dan Masalah Sosial Budaya', 'Jenis-jenis Keragaman Budaya di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 4: Keragaman Budaya dan Masalah Sosial Budaya', 'Nilai Persatuan dalam Keragaman'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 4: Keragaman Budaya dan Masalah Sosial Budaya', 'Masalah Sosial Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 4: Keragaman Budaya dan Masalah Sosial Budaya', 'Upaya Menjaga Keutuhan Sosial Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Pemberdayaan Masyarakat', 'Arti dan Tujuan Pemberdayaan Masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Pemberdayaan Masyarakat', 'Lembaga Pemberdayaan dan Program Pemerintah (UMKM, koperasi, CSR)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Pemberdayaan Masyarakat', 'Literasi Keuangan Dasar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Pemberdayaan Masyarakat', 'Kewirausahaan dan Kemandirian Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Pemberdayaan Masyarakat', 'Peran Komunitas Sosial dalam Pemberdayaan');

-- Grade 8
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Keragaman Alam Indonesia', 'Kondisi Geografis Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Keragaman Alam Indonesia', 'Proses Geografis dan Dampaknya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Keragaman Alam Indonesia', 'Jenis dan Persebaran Sumber Daya Alam'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Keragaman Alam Indonesia', 'Potensi SDA dan Pemanfaatannya untuk Kesejahteraan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Pemanfaatan dan Pelestarian Sumber Daya Alam', 'Kebutuhan Manusia dan SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Pemanfaatan dan Pelestarian Sumber Daya Alam', 'Bentuk Pemanfaatan SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Pemanfaatan dan Pelestarian Sumber Daya Alam', 'Dampak Pemanfaatan SDA yang Tidak Bijak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Pemanfaatan dan Pelestarian Sumber Daya Alam', 'Upaya Pelestarian dan Pengelolaan SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Sumber Daya Manusia (SDM)', 'Pengertian dan Karakteristik SDM'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Sumber Daya Manusia (SDM)', 'Kualitas SDM Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Sumber Daya Manusia (SDM)', 'Tantangan SDM di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Sumber Daya Manusia (SDM)', 'Upaya Peningkatan Kualitas SDM'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Sumber Daya Manusia (SDM)', 'Peran SDM dalam Pembangunan Berkelanjutan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Peran Lembaga Sosial dalam Kehidupan Masyarakat', 'Pengertian dan Fungsi Lembaga Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Peran Lembaga Sosial dalam Kehidupan Masyarakat', 'Jenis Lembaga Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Peran Lembaga Sosial dalam Kehidupan Masyarakat', 'Peran Lembaga Sosial dalam Pengelolaan SDA dan SDM'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Peran Lembaga Sosial dalam Kehidupan Masyarakat', 'Perubahan Sosial dan Dinamika Lembaga Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 4: Peran Lembaga Sosial dalam Kehidupan Masyarakat', 'Nilai dan Norma dalam Lembaga Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Interaksi dengan Bangsa Asing', 'Pengaruh Letak Strategis Indonesia dalam Perdagangan Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Interaksi dengan Bangsa Asing', 'Sejarah Awal Interaksi dengan Bangsa Asing'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Interaksi dengan Bangsa Asing', 'Dampak Sosial Budaya dan Ekonomi dari Interaksi Asing'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Interaksi dengan Bangsa Asing', 'Globalisasi dan Identitas Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 1', 'Bab 5: Interaksi dengan Bangsa Asing', 'Strategi Menjaga Jati Diri Budaya di Era Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Keragaman dan Kemajemukan Masyarakat Indonesia', 'Keragaman Aktivitas Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Keragaman dan Kemajemukan Masyarakat Indonesia', 'Perdagangan Antar Pulau dan Peran Transportasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Keragaman dan Kemajemukan Masyarakat Indonesia', 'Dampak Kolonialisme terhadap Kehidupan Ekonomi dan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Keragaman dan Kemajemukan Masyarakat Indonesia', 'Konflik Sosial dan Upaya Integrasi Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Pergerakan Kebangsaan Menuju Kemerdekaan', 'Latar Belakang Kedatangan Bangsa Barat ke Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Pergerakan Kebangsaan Menuju Kemerdekaan', 'Perlawanan Daerah terhadap Penjajah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Pergerakan Kebangsaan Menuju Kemerdekaan', 'Peran Tokoh-Tokoh Pergerakan Nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Pergerakan Kebangsaan Menuju Kemerdekaan', 'Tumbuh dan Berkembangnya Nasionalisme Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Pembangunan dan Pemerataan', 'Konsep dan Tujuan Pembangunan Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Pembangunan dan Pemerataan', 'Pemerataan Pembangunan Antar Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Pembangunan dan Pemerataan', 'Dampak Positif dan Negatif Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Pembangunan dan Pemerataan', 'Tantangan Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 4: Dinamika Penduduk dan Perubahan Sosial', 'Pertumbuhan Penduduk dan Dampaknya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 4: Dinamika Penduduk dan Perubahan Sosial', 'Persebaran Penduduk dan Urbanisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 4: Dinamika Penduduk dan Perubahan Sosial', 'Perubahan Sosial karena Teknologi dan Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 4: Dinamika Penduduk dan Perubahan Sosial', 'Peran Lembaga Sosial dalam Menjaga Keseimbangan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Pelaku Ekonomi, Pasar, dan Pajak', 'Pelaku Ekonomi: Rumah Tangga, Perusahaan, Pemerintah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Pelaku Ekonomi, Pasar, dan Pajak', 'Fungsi dan Jenis Pasar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Pelaku Ekonomi, Pasar, dan Pajak', 'Mekanisme Pasar dan Harga'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Pelaku Ekonomi, Pasar, dan Pajak', 'Pajak dan Fungsinya dalam Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 5: Pelaku Ekonomi, Pasar, dan Pajak', 'Literasi Keuangan Dasar untuk Pelajar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 6: Hubungan Sosial, Pranata Sosial, dan Ketenagakerjaan', 'Bentuk Interaksi Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 6: Hubungan Sosial, Pranata Sosial, dan Ketenagakerjaan', 'Pranata Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 6: Hubungan Sosial, Pranata Sosial, dan Ketenagakerjaan', 'Masalah Ketenagakerjaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 8 (SMP)', 'Semester 2', 'Bab 6: Hubungan Sosial, Pranata Sosial, dan Ketenagakerjaan', 'Hak dan Kewajiban Pekerja serta Peran Pemerintah');

-- Grade 9
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Manusia dan Perubahan', 'Pengertian dan Bentuk Perubahan Sosial Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Manusia dan Perubahan', 'Faktor Pendorong dan Penghambat Perubahan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Manusia dan Perubahan', 'Dampak Modernisasi dan Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Manusia dan Perubahan', 'Adaptasi Masyarakat terhadap Perubahan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Manusia dan Perubahan', 'Pelestarian Nilai Kearifan Lokal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Perkembangan Ekonomi Digital dan Literasi Finansial', 'Perkembangan Sistem Ekonomi di Era Digital'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Perkembangan Ekonomi Digital dan Literasi Finansial', 'Karakteristik Ekonomi Digital'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Perkembangan Ekonomi Digital dan Literasi Finansial', 'Literasi Finansial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Perkembangan Ekonomi Digital dan Literasi Finansial', 'Peran Pelajar dalam Ekonomi Digital'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Perkembangan Ekonomi Digital dan Literasi Finansial', 'Keamanan Digital dan Etika Transaksi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Tantangan Pembangunan Indonesia', 'Pengertian dan Tujuan Pembangunan Nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Tantangan Pembangunan Indonesia', 'Masalah dalam Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Tantangan Pembangunan Indonesia', 'Upaya Mengatasi Masalah Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Tantangan Pembangunan Indonesia', 'Pembangunan Berkelanjutan (SDGs)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Tantangan Pembangunan Indonesia', 'Pemerataan Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Interaksi Antarnegara di Asia dan Dunia', 'Bentuk Interaksi Antarnegara'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Interaksi Antarnegara di Asia dan Dunia', 'Organisasi Regional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Interaksi Antarnegara di Asia dan Dunia', 'Perdagangan Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Interaksi Antarnegara di Asia dan Dunia', 'Dampak Interaksi Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Interaksi Antarnegara di Asia dan Dunia', 'Peran Indonesia dalam Hubungan Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Perubahan Sosial Budaya Global dan Pengaruhnya', 'Perubahan Gaya Hidup di Era Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Perubahan Sosial Budaya Global dan Pengaruhnya', 'Dampak Globalisasi terhadap Pendidikan, Keluarga, dan Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Perubahan Sosial Budaya Global dan Pengaruhnya', 'Globalisasi vs Tradisi Lokal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Perubahan Sosial Budaya Global dan Pengaruhnya', 'Peran Media Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Perubahan Sosial Budaya Global dan Pengaruhnya', 'Strategi Menyaring Budaya Asing'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Tantangan Pembangunan Indonesia', 'Sejarah Pembangunan di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Tantangan Pembangunan Indonesia', 'Permasalahan dalam Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Tantangan Pembangunan Indonesia', 'Peran Serta Masyarakat dalam Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Kerjasama Dunia', 'Perdagangan Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Kerjasama Dunia', 'Ekonomi Kreatif dan Daya Saing Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Kerjasama Dunia', 'Kerjasama Regional dan Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Perkembangan Ekonomi Digital', 'Transformasi Ekonomi di Era Digital'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Perkembangan Ekonomi Digital', 'Literasi Keuangan Digital'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Perkembangan Ekonomi Digital', 'Peran UMKM dan E-Commerce'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Perkembangan Ekonomi Digital', 'Ekonomi Digital dan Keadilan Akses'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Manusia dan Perubahan Sosial Budaya', 'Pengertian Perubahan Sosial Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Manusia dan Perubahan Sosial Budaya', 'Modernisasi dan Dampaknya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Manusia dan Perubahan Sosial Budaya', 'Adaptasi Masyarakat terhadap Perubahan Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Manusia dan Perubahan Sosial Budaya', 'Pelestarian Kearifan Lokal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Manusia dan Perubahan Sosial Budaya', 'Peran Pemuda dalam Menjaga Identitas Budaya');

-- Grade 10
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Manusia, Ruang, dan Waktu', 'Konsep Dasar Sejarah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Manusia, Ruang, dan Waktu', 'Peristiwa Sejarah dalam Konteks Waktu dan Ruang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Manusia, Ruang, dan Waktu', 'Pentingnya Memahami Sejarah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Perkembangan Kehidupan Manusia', 'Evolusi Kehidupan Manusia Purba'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Perkembangan Kehidupan Manusia', 'Pengaruh Lingkungan terhadap Peradaban'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Perkembangan Kehidupan Manusia', 'Adaptasi Manusia terhadap Alam'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Historiografi', 'Pengertian dan Jenis Historiografi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Historiografi', 'Sumber Sejarah dan Penulisan Sejarah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Historiografi', 'Kritik Sumber dan Rekonstruksi Sejarah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Kehidupan Masyarakat Praaksara, Hindu-Buddha, Islam', 'Kehidupan Sosial Ekonomi dan Budaya Praaksara'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Kehidupan Masyarakat Praaksara, Hindu-Buddha, Islam', 'Kerajaan Hindu-Buddha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sejarah: Kehidupan Masyarakat Praaksara, Hindu-Buddha, Islam', 'Perkembangan Islam dan Akulturasi Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sosiologi: Sosiologi sebagai Ilmu', 'Pengertian dan Ciri-ciri Sosiologi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sosiologi: Sosiologi sebagai Ilmu', 'Objek dan Fungsi Sosiologi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sosiologi: Sosiologi sebagai Ilmu', 'Peran Sosiologi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sosiologi: Sistem Sosial Masyarakat', 'Nilai dan Norma Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sosiologi: Sistem Sosial Masyarakat', 'Struktur Sosial dan Status Peran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sosiologi: Sistem Sosial Masyarakat', 'Sosialisasi dalam Kehidupan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sosiologi: Interaksi Sosial dan Dinamika Kehidupan', 'Bentuk-bentuk Interaksi Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sosiologi: Interaksi Sosial dan Dinamika Kehidupan', 'Faktor Perubahan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Sosiologi: Interaksi Sosial dan Dinamika Kehidupan', 'Dampak Dinamika Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Konsep Dasar Ilmu Ekonomi', 'Pengertian Ilmu Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Konsep Dasar Ilmu Ekonomi', 'Kelangkaan dan Pilihan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Konsep Dasar Ilmu Ekonomi', 'Biaya Peluang dan Skala Prioritas'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Permasalahan dan Sistem Ekonomi', 'Masalah Pokok Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Permasalahan dan Sistem Ekonomi', 'Sistem Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Permasalahan dan Sistem Ekonomi', 'Perbandingan Sistem Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Peran Pelaku Ekonomi', 'Rumah Tangga Konsumen dan Produsen'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Peran Pelaku Ekonomi', 'Pemerintah dan Masyarakat Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Peran Pelaku Ekonomi', 'Circular Flow of Income'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Keseimbangan dan Struktur Pasar', 'Hukum Permintaan dan Penawaran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Keseimbangan dan Struktur Pasar', 'Keseimbangan Harga'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Keseimbangan dan Struktur Pasar', 'Jenis-jenis Struktur Pasar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Lembaga Jasa Keuangan', 'Fungsi dan Peran Bank Sentral'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Lembaga Jasa Keuangan', 'Sistem Pembayaran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Lembaga Jasa Keuangan', 'Literasi Keuangan Dasar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Badan Usaha dan Perkoperasian', 'Jenis-jenis Badan Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Ekonomi: Badan Usaha dan Perkoperasian', 'Fungsi dan Prinsip Koperasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Konsep dan Pendekatan Geografi', 'Konsep Dasar Geografi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Konsep dan Pendekatan Geografi', 'Pendekatan Geografi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Pengetahuan Dasar Geografi', 'Unsur Geosfer'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Pengetahuan Dasar Geografi', 'Keterkaitan Unsur dalam Geosfer'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Keragaman Alam Indonesia', 'Iklim dan Cuaca'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Keragaman Alam Indonesia', 'Flora dan Fauna'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Keragaman Alam Indonesia', 'Potensi dan Persebaran SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Pemanfaatan Sumber Daya Alam', 'Jenis dan Pemanfaatan SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Pemanfaatan Sumber Daya Alam', 'Pengelolaan SDA Berkelanjutan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Pemanfaatan Sumber Daya Alam', 'Dampak Eksploitasi SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Kondisi Geografis dan Interaksi Lingkungan', 'Hubungan Manusia dan Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Kondisi Geografis dan Interaksi Lingkungan', 'Bencana Alam dan Mitigasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 1', 'Geografi: Kondisi Geografis dan Interaksi Lingkungan', 'Interaksi Ruang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Peradaban Awal Dunia dan Nusantara', 'Awal Mula Kehidupan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Peradaban Awal Dunia dan Nusantara', 'Peradaban Sungai'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Peradaban Awal Dunia dan Nusantara', 'Peradaban Klasik Dunia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Peradaban Awal Dunia dan Nusantara', 'Peradaban Awal di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Kolonialisme dan Imperialisme', 'Latar Belakang Kolonialisme'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Kolonialisme dan Imperialisme', 'Dampak Penjajahan di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Kolonialisme dan Imperialisme', 'Perlawanan Rakyat Nusantara'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Pergerakan Nasional dan Kebangkitan Bangsa', 'Lahirnya Kesadaran Kebangsaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Pergerakan Nasional dan Kebangkitan Bangsa', 'Peran Organisasi Pergerakan Nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sejarah: Pergerakan Nasional dan Kebangkitan Bangsa', 'Sumpah Pemuda'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sosiologi: Individu dalam Masyarakat', 'Proses Sosialisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sosiologi: Individu dalam Masyarakat', 'Peran dan Status Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sosiologi: Individu dalam Masyarakat', 'Keluarga sebagai Agen Sosialisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sosiologi: Nilai, Norma, dan Kontrol Sosial', 'Jenis-jenis Nilai dan Norma'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sosiologi: Nilai, Norma, dan Kontrol Sosial', 'Fungsi dan Bentuk Kontrol Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sosiologi: Nilai, Norma, dan Kontrol Sosial', 'Penyimpangan dan Sanksi Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sosiologi: Perubahan Sosial dan Globalisasi', 'Faktor-faktor Perubahan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sosiologi: Perubahan Sosial dan Globalisasi', 'Dampak Perubahan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Sosiologi: Perubahan Sosial dan Globalisasi', 'Tantangan Globalisasi dan Kearifan Lokal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Ekonomi: Kegiatan Ekonomi dan Kebutuhan Manusia', 'Jenis Kebutuhan dan Kelangkaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Ekonomi: Kegiatan Ekonomi dan Kebutuhan Manusia', 'Kegiatan Produksi, Distribusi, Konsumsi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Ekonomi: Kegiatan Ekonomi dan Kebutuhan Manusia', 'Faktor Produksi dan Biaya Peluang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Ekonomi: Sistem Ekonomi dan Peran Pemerintah', 'Sistem Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Ekonomi: Sistem Ekonomi dan Peran Pemerintah', 'Intervensi Pemerintah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Ekonomi: Sistem Ekonomi dan Peran Pemerintah', 'APBN, APBD'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Ekonomi: Permasalahan Ekonomi di Indonesia', 'Pengangguran dan Kemiskinan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Ekonomi: Permasalahan Ekonomi di Indonesia', 'Inflasi dan Deflasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Ekonomi: Permasalahan Ekonomi di Indonesia', 'Ketimpangan Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Geografi: Dinamika Litosfer', 'Proses Pembentukan Litosfer'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Geografi: Dinamika Litosfer', 'Bencana Alam Litosfer'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Geografi: Dinamika Litosfer', 'Mitigasi Bencana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Geografi: Dinamika Atmosfer dan Hidrosfer', 'Perubahan Iklim dan Cuaca'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Geografi: Dinamika Atmosfer dan Hidrosfer', 'Sumber Daya Air'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Geografi: Dinamika Atmosfer dan Hidrosfer', 'Pola Curah Hujan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Geografi: Interaksi Manusia dengan Lingkungan', 'Pola Permukiman'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Geografi: Interaksi Manusia dengan Lingkungan', 'Konversi Lahan dan Urbanisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 10 (SMA)', 'Semester 2', 'Geografi: Interaksi Manusia dengan Lingkungan', 'Isu-isu Lingkungan Global');

-- Grade 11
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Pembentukan Kelompok Sosial', 'Pengertian dan Ciri Kelompok Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Pembentukan Kelompok Sosial', 'Jenis Kelompok Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Pembentukan Kelompok Sosial', 'Faktor Pembentuk Kelompok Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Permasalahan Sosial di Masyarakat', 'Pengertian Masalah Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Permasalahan Sosial di Masyarakat', 'Jenis Masalah Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Permasalahan Sosial di Masyarakat', 'Penyebab dan Dampak Masalah Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Permasalahan Sosial di Masyarakat', 'Upaya Penanggulangan Masalah Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Kesetaraan, Perbedaan, dan Harmoni Sosial', 'Pengertian Kesetaraan dan Keadilan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Kesetaraan, Perbedaan, dan Harmoni Sosial', 'Bentuk Perbedaan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Kesetaraan, Perbedaan, dan Harmoni Sosial', 'Tantangan Harmoni Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Kesetaraan, Perbedaan, dan Harmoni Sosial', 'Strategi Membangun Toleransi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sosiologi: Kesetaraan, Perbedaan, dan Harmoni Sosial', 'Konsep Multikulturalisme'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Globalisasi dan Isu-Isu Global', 'Pengertian Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Globalisasi dan Isu-Isu Global', 'Ciri dan Proses Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Globalisasi dan Isu-Isu Global', 'Dampak Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Globalisasi dan Isu-Isu Global', 'Tantangan dan Peluang Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Perekonomian Global', 'Perdagangan Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Perekonomian Global', 'Global Supply Chain'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Perekonomian Global', 'Perusahaan Multinasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Perekonomian Global', 'Ketimpangan Ekonomi Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Lingkungan Global', 'Isu-isu Lingkungan Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Lingkungan Global', 'Upaya Internasional Mengatasi Krisis Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Lingkungan Global', 'Peran Warga Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Hubungan Internasional', 'Bentuk Kerjasama Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Hubungan Internasional', 'Peran Lembaga Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Hubungan Internasional', 'Diplomasi dan Keamanan Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Geografi: Hubungan Internasional', 'Isu Global Kontemporer'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Badan Usaha', 'Pengertian Badan Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Badan Usaha', 'Bentuk Badan Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Badan Usaha', 'Fungsi dan Peran Badan Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Badan Usaha', 'Etika Bisnis dan CSR'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Pendapatan Nasional', 'Konsep Pendapatan Nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Pendapatan Nasional', 'Perhitungan dan Indikator Kesejahteraan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Pendapatan Nasional', 'Distribusi Pendapatan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Pendapatan Nasional', 'Strategi Mengurangi Ketimpangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Ketenagakerjaan', 'Jenis Tenaga Kerja'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Ketenagakerjaan', 'Indikator Ketenagakerjaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Ketenagakerjaan', 'Permasalahan Ketenagakerjaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Ketenagakerjaan', 'Program Penanggulangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Uang, Indeks Harga, dan Inflasi', 'Pengertian Uang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Uang, Indeks Harga, dan Inflasi', 'Indeks Harga Konsumen (IHK)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Uang, Indeks Harga, dan Inflasi', 'Penyebab dan Dampak Inflasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Uang, Indeks Harga, dan Inflasi', 'Strategi Mengendalikan Inflasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Tujuan Kebijakan Moneter'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Peran Bank Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Tujuan Kebijakan Fiskal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Fungsi APBN dan APBD'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Instrumen Kebijakan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Imperialisme dan Kolonialisme', 'Pengertian Imperialisme dan Kolonialisme'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Imperialisme dan Kolonialisme', 'Faktor Pendorong Bangsa Barat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Imperialisme dan Kolonialisme', 'Kedatangan Bangsa Eropa'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Imperialisme dan Kolonialisme', 'VOC dan Monopoli Dagang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Perlawanan Terhadap Kolonialisme', 'Perlawanan Daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Perlawanan Terhadap Kolonialisme', 'Ciri Perlawanan Tradisional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Perlawanan Terhadap Kolonialisme', 'Kegagalan dan Pembelajaran'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Perlawanan Terhadap Kolonialisme', 'Lahirnya Kesadaran Nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Awal Munculnya Nasionalisme', 'Faktor Lahirnya Nasionalisme'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Awal Munculnya Nasionalisme', 'Peran Pers, Pendidikan, Tokoh'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 1', 'Sejarah: Awal Munculnya Nasionalisme', 'Organisasi Modern'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Badan Usaha dalam Perekonomian', 'Pengertian dan Fungsi Badan Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Badan Usaha dalam Perekonomian', 'Bentuk-Bentuk Badan Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Badan Usaha dalam Perekonomian', 'Peran Badan Usaha'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Badan Usaha dalam Perekonomian', 'Etika Bisnis dan CSR'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Pendapatan Nasional dan Kesenjangan', 'Konsep Pendapatan Nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Pendapatan Nasional dan Kesenjangan', 'Metode Perhitungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Pendapatan Nasional dan Kesenjangan', 'Distribusi Pendapatan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Pendapatan Nasional dan Kesenjangan', 'Masalah Ketimpangan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Ketenagakerjaan', 'Jenis-jenis Tenaga Kerja'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Ketenagakerjaan', 'Indikator Ketenagakerjaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Ketenagakerjaan', 'Permasalahan dan Solusi Ketenagakerjaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Ketenagakerjaan', 'UU Ketenagakerjaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Teori Uang, Indeks Harga, dan Inflasi', 'Fungsi dan Jenis Uang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Teori Uang, Indeks Harga, dan Inflasi', 'Indeks Harga Konsumen (IHK)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Teori Uang, Indeks Harga, dan Inflasi', 'Penyebab dan Dampak Inflasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Teori Uang, Indeks Harga, dan Inflasi', 'Upaya Mengendalikan Inflasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Tujuan Kebijakan Moneter'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Instrumen Kebijakan Moneter'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Peran Bank Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Tujuan Kebijakan Fiskal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Instrumen Kebijakan Fiskal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Ekonomi: Kebijakan Moneter dan Fiskal', 'Peran APBN dan APBD'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Lingkungan Hidup', 'Pengertian dan Komponen Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Lingkungan Hidup', 'Interaksi Manusia dan Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Lingkungan Hidup', 'Masalah Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Lingkungan Hidup', 'Upaya Pelestarian Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Mitigasi dan Adaptasi Bencana Alam', 'Jenis Bencana Alam'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Mitigasi dan Adaptasi Bencana Alam', 'Faktor Penyebab dan Dampak'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Mitigasi dan Adaptasi Bencana Alam', 'Mitigasi Bencana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Mitigasi dan Adaptasi Bencana Alam', 'Adaptasi Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Isu-Isu Global', 'Globalisasi dan Dampaknya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Isu-Isu Global', 'Perdagangan Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Isu-Isu Global', 'Krisis Lingkungan Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Isu-Isu Global', 'Kerja Sama Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Geografi: Isu-Isu Global', 'Peran Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Masalah Sosial di Masyarakat', 'Pengertian Masalah Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Masalah Sosial di Masyarakat', 'Faktor Penyebab Masalah Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Masalah Sosial di Masyarakat', 'Contoh Masalah Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Masalah Sosial di Masyarakat', 'Upaya Penanggulangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Interaksi Sosial', 'Pengertian dan Syarat Interaksi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Interaksi Sosial', 'Bentuk Interaksi Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Interaksi Sosial', 'Agen Sosialisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Interaksi Sosial', 'Interaksi di Era Digital'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Konflik dan Integrasi Sosial', 'Pengertian dan Penyebab Konflik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Konflik dan Integrasi Sosial', 'Bentuk Konflik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Konflik dan Integrasi Sosial', 'Dampak Konflik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Konflik dan Integrasi Sosial', 'Proses Integrasi Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sosiologi: Konflik dan Integrasi Sosial', 'Strategi Kehidupan Harmonis'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sejarah: Pendudukan Jepang dan Persiapan Kemerdekaan', 'Pendudukan Jepang di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sejarah: Pendudukan Jepang dan Persiapan Kemerdekaan', 'Perlawanan terhadap Jepang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 11 (SMA)', 'Semester 2', 'Sejarah: Pendudukan Jepang dan Persiapan Kemerdekaan', 'Persiapan Kemerdekaan Indonesia');

-- Grade 12
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Perubahan Sosial', 'Pengertian Perubahan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Perubahan Sosial', 'Faktor Perubahan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Perubahan Sosial', 'Jenis Perubahan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Perubahan Sosial', 'Dampak Perubahan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Globalisasi', 'Konsep Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Globalisasi', 'Aspek Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Globalisasi', 'Dampak Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Globalisasi', 'Respon Masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Ketimpangan Sosial', 'Pengertian Ketimpangan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Ketimpangan Sosial', 'Faktor Penyebab Ketimpangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Ketimpangan Sosial', 'Dampak Ketimpangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Ketimpangan Sosial', 'Strategi Mengatasi Ketimpangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Kearifan Lokal', 'Pengertian Kearifan Lokal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Kearifan Lokal', 'Peran Kearifan Lokal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Kearifan Lokal', 'Kearifan Lokal dalam Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sosiologi: Kearifan Lokal', 'Contoh Kearifan Lokal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Pertumbuhan Ekonomi', 'Pengertian Pertumbuhan Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Pertumbuhan Ekonomi', 'Indikator Pertumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Pertumbuhan Ekonomi', 'Faktor Pertumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Pertumbuhan Ekonomi', 'Masalah Pertumbuhan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Pembangunan Ekonomi', 'Pengertian Pembangunan Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Pembangunan Ekonomi', 'Perbedaan Pertumbuhan dan Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Pembangunan Ekonomi', 'Strategi Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Pembangunan Ekonomi', 'Tantangan Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Peran Lembaga Jasa Keuangan', 'Jenis Lembaga Keuangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Peran Lembaga Jasa Keuangan', 'Fungsi Lembaga Keuangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Peran Lembaga Jasa Keuangan', 'Otoritas Jasa Keuangan (OJK)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Peran Lembaga Jasa Keuangan', 'Inklusi dan Literasi Keuangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Anggaran Pendapatan dan Belanja Negara (APBN)', 'Fungsi APBN'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Anggaran Pendapatan dan Belanja Negara (APBN)', 'Proses Penyusunan APBN'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Anggaran Pendapatan dan Belanja Negara (APBN)', 'Struktur APBN'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Ekonomi: Anggaran Pendapatan dan Belanja Negara (APBN)', 'Peran APBN'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Teori Wilayah', 'Pengertian Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Teori Wilayah', 'Teori Perkembangan Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Teori Wilayah', 'Jenis Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Teori Wilayah', 'Perencanaan Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Pemanfaatan dan Kelestarian Lingkungan', 'Pembangunan Berkelanjutan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Pemanfaatan dan Kelestarian Lingkungan', 'Pengelolaan SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Pemanfaatan dan Kelestarian Lingkungan', 'Prinsip Pelestarian (3R)'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Pemanfaatan dan Kelestarian Lingkungan', 'Konflik Pemanfaatan SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Perkembangan Wilayah', 'Faktor Perkembangan Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Perkembangan Wilayah', 'Wilayah Maju vs Tertinggal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Perkembangan Wilayah', 'Ketimpangan Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Perkembangan Wilayah', 'Studi Kasus Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Mitigasi Bencana', 'Jenis Bencana'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Mitigasi Bencana', 'Tahapan Mitigasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Mitigasi Bencana', 'Peran Masyarakat dan Pemerintah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Geografi: Mitigasi Bencana', 'Edukasi dan Teknologi Mitigasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perkembangan Bangsa Indonesia', 'Masa Awal Kemerdekaan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perkembangan Bangsa Indonesia', 'Demokrasi Liberal, Terpimpin, Orde Baru'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perkembangan Bangsa Indonesia', 'Reformasi dan Era Kontemporer'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perjuangan Bangsa Indonesia', 'Menghadapi Agresi Militer Belanda'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perjuangan Bangsa Indonesia', 'Konferensi Meja Bundar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perjuangan Bangsa Indonesia', 'Menegakkan Demokrasi dan HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Peran Indonesia di Kancah Internasional', 'Politik Luar Negeri Bebas Aktif'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Peran Indonesia di Kancah Internasional', 'Peran dalam Organisasi Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Peran Indonesia di Kancah Internasional', 'Diplomasi dan Perdamaian Dunia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Peran Indonesia di Kancah Internasional', 'Tanggung Jawab Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perkembangan IPTEK', 'IPTEK di Masa Orde Baru dan Reformasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perkembangan IPTEK', 'Inovasi dan Transformasi Digital'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perkembangan IPTEK', 'Dampak IPTEK'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 1', 'Sejarah: Perkembangan IPTEK', 'Tantangan Etika dan Regulasi IPTEK'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Pasar Modal dan Investasi', 'Pengertian Pasar Modal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Pasar Modal dan Investasi', 'Instrumen Pasar Modal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Pasar Modal dan Investasi', 'Mekanisme Transaksi Saham'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Pasar Modal dan Investasi', 'Manfaat dan Risiko Investasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Pasar Modal dan Investasi', 'Peran OJK dan BEI'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Lembaga Keuangan', 'Bank vs Non-Bank'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Lembaga Keuangan', 'Fungsi dan Jenis Bank'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Lembaga Keuangan', 'Lembaga Non-Bank'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Lembaga Keuangan', 'Peran Lembaga Keuangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Perdagangan Internasional', 'Teori Perdagangan Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Perdagangan Internasional', 'Ekspor dan Impor'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Perdagangan Internasional', 'Perjanjian Perdagangan Bebas'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Perdagangan Internasional', 'Dampak Perdagangan Global'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Bank Indonesia dan Kebijakan Moneter', 'Fungsi Bank Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Bank Indonesia dan Kebijakan Moneter', 'Instrumen Kebijakan Moneter'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Bank Indonesia dan Kebijakan Moneter', 'Stabilitas Rupiah dan Inflasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Bank Indonesia dan Kebijakan Moneter', 'Peran BI dalam Pertumbuhan Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Laporan Keuangan Sederhana', 'Tujuan Laporan Keuangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Laporan Keuangan Sederhana', 'Komponen Laporan Keuangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Laporan Keuangan Sederhana', 'Prinsip Akuntansi Dasar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Ekonomi: Laporan Keuangan Sederhana', 'Contoh Laporan Keuangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Peta, Penginderaan Jauh, dan SIG', 'Jenis dan Fungsi Peta'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Peta, Penginderaan Jauh, dan SIG', 'Interpretasi Citra Penginderaan Jauh'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Peta, Penginderaan Jauh, dan SIG', 'Penggunaan SIG'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Peta, Penginderaan Jauh, dan SIG', 'Aplikasi Teknologi Geospasial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Kerjasama Internasional', 'Kerjasama Negara Maju dan Berkembang'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Kerjasama Internasional', 'Bentuk Kerjasama'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Kerjasama Internasional', 'Studi Kasus Organisasi Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Kerjasama Internasional', 'Manfaat dan Tantangan Kerjasama'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Perubahan Iklim dan Lingkungan Global', 'Penyebab Perubahan Iklim'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Perubahan Iklim dan Lingkungan Global', 'Dampak Perubahan Iklim'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Perubahan Iklim dan Lingkungan Global', 'Upaya Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Perubahan Iklim dan Lingkungan Global', 'Kontribusi Individu dan Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Perkembangan Wilayah dan Potensi SDA', 'Konsep Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Perkembangan Wilayah dan Potensi SDA', 'Potensi SDA'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Perkembangan Wilayah dan Potensi SDA', 'Pemerataan Pembangunan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Perkembangan Wilayah dan Potensi SDA', 'Studi Kasus Kawasan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Analisis Keruangan', 'Konsep Analisis Keruangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Analisis Keruangan', 'Analisis Sosial, Ekonomi, Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Analisis Keruangan', 'Pemetaan Potensi dan Masalah'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Geografi: Analisis Keruangan', 'Perencanaan Berbasis Data Geospasial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Perubahan Sosial dan Globalisasi', 'Konsep Perubahan Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Perubahan Sosial dan Globalisasi', 'Globalisasi dan Transformasi Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Perubahan Sosial dan Globalisasi', 'Modernisasi dan Dampaknya'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Perubahan Sosial dan Globalisasi', 'Tantangan Identitas Budaya Lokal'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Lembaga Sosial dan Interaksi', 'Fungsi Lembaga Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Lembaga Sosial dan Interaksi', 'Jenis Lembaga Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Lembaga Sosial dan Interaksi', 'Proses Sosialisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Lembaga Sosial dan Interaksi', 'Peran Lembaga Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Penelitian Sosial', 'Langkah Penelitian Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Penelitian Sosial', 'Teknik Pengumpulan Data'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Penelitian Sosial', 'Penyusunan Laporan Penelitian'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Penelitian Sosial', 'Implementasi Hasil Penelitian'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Penyimpangan Sosial dan Pengendalian', 'Pengertian Penyimpangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Penyimpangan Sosial dan Pengendalian', 'Penyebab Penyimpangan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Penyimpangan Sosial dan Pengendalian', 'Bentuk Pengendalian Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sosiologi: Penyimpangan Sosial dan Pengendalian', 'Lembaga Pengendali'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Proklamasi Kemerdekaan', 'Latar Belakang Proklamasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Proklamasi Kemerdekaan', 'Makna Proklamasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Proklamasi Kemerdekaan', 'Tokoh dan Dokumen Penting'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Proklamasi Kemerdekaan', 'Respon Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perjuangan Mempertahankan Kemerdekaan', 'Agresi Militer Belanda'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perjuangan Mempertahankan Kemerdekaan', 'Diplomasi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perjuangan Mempertahankan Kemerdekaan', 'Peran TNI dan Rakyat'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perjuangan Mempertahankan Kemerdekaan', 'Konferensi Meja Bundar'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perkembangan Politik dan Ekonomi Pasca-Kemerdekaan', 'Sistem Pemerintahan'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perkembangan Politik dan Ekonomi Pasca-Kemerdekaan', 'Demokrasi di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perkembangan Politik dan Ekonomi Pasca-Kemerdekaan', 'Sistem Ekonomi Nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perkembangan Politik dan Ekonomi Pasca-Kemerdekaan', 'Krisis dan Stabilitas Politik'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perkembangan Dunia dan Pengaruhnya', 'Perang Dingin'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perkembangan Dunia dan Pengaruhnya', 'Konflik Regional dan Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perkembangan Dunia dan Pengaruhnya', 'Dampak Globalisasi Politik dan Ekonomi'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Perkembangan Dunia dan Pengaruhnya', 'Perubahan Tata Dunia'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Peran Indonesia dalam Hubungan Internasional', 'Politik Luar Negeri Bebas Aktif'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Peran Indonesia dalam Hubungan Internasional', 'Peran dalam Organisasi Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Peran Indonesia dalam Hubungan Internasional', 'Diplomasi Budaya, Ekonomi, Perdamaian'),
('Kurikulum Merdeka Belajar', 'id', 'Ilmu Pengetahuan Sosial (IPS)', 'Grade 12 (SMA)', 'Semester 2', 'Sejarah: Peran Indonesia dalam Hubungan Internasional', 'Isu Kontemporer');
