-- Seed script for Pendidikan Pancasila curriculum
-- Language: Indonesian
-- Curriculum Type: Kurikulum Merdeka Belajar

-- Clear existing Pendidikan Pancasila data to prevent duplicates
DELETE FROM public.curriculum WHERE subject = 'Pendidikan Pancasila';

-- Grade 1
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 1: Mengenal Pancasila, Dasar Negara Kita', 'Apa Itu Pancasila?'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 1: Mengenal Pancasila, Dasar Negara Kita', 'Bunyi dan Urutan Sila-sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 1: Mengenal Pancasila, Dasar Negara Kita', 'Lambang Tiap Sila dalam Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 2: Garuda Pancasila, Lambang Negara Kita', 'Mengenal Bentuk Garuda Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 2: Garuda Pancasila, Lambang Negara Kita', 'Warna dan Simbol pada Garuda Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 2: Garuda Pancasila, Lambang Negara Kita', 'Arti Pita “Bhinneka Tunggal Ika”'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 3: Aku Anak Pancasila', 'Penerapan Sila Ke-1 sampai Ke-5'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 3: Aku Anak Pancasila', 'Bermain Peran Nilai-nilai Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 4: Taat Aturan, Hidup Nyaman', 'Aturan di Rumah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 4: Taat Aturan, Hidup Nyaman', 'Aturan di Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 4: Taat Aturan, Hidup Nyaman', 'Aturan di Tempat Bermain'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 5: Lingkunganku Bersih dan Asri', 'Mengenal Lingkungan Sekitar'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 5: Lingkunganku Bersih dan Asri', 'Menjaga Kebersihan Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 5: Lingkunganku Bersih dan Asri', 'Peduli Terhadap Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 6: Hak dan Kewajibanku', 'Hak Sebagai Anak di Rumah dan Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 6: Hak dan Kewajibanku', 'Kewajiban sebagai Anak'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 6: Hak dan Kewajibanku', 'Menyeimbangkan Hak dan Kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 7: Ayo Bekerja Sama!', 'Apa Itu Kerja Sama?'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 7: Ayo Bekerja Sama!', 'Contoh Kerja Sama di Rumah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 1', 'Bab 7: Ayo Bekerja Sama!', 'Contoh Kerja Sama di Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 1: Aku Cinta Lingkunganku', 'Mengenal Lingkungan Sekitar'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 1: Aku Cinta Lingkunganku', 'Menjaga Kebersihan Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 1: Aku Cinta Lingkunganku', 'Hidup Rukun dan Damai'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 2: Aku Suka Bergotong Royong', 'Apa Itu Gotong Royong?'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 2: Aku Suka Bergotong Royong', 'Bergotong Royong di Rumah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 2: Aku Suka Bergotong Royong', 'Bergotong Royong di Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 3: Mengenal Lingkungan Rumah dan Tetanggaku', 'Mengenal Denah Rumah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 3: Mengenal Lingkungan Rumah dan Tetanggaku', 'Menjaga Kebersihan Rumah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 3: Mengenal Lingkungan Rumah dan Tetanggaku', 'Mengenal dan Menyapa Tetangga'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 4: Aku Peduli Lingkungan Sekitar', 'Mengenal Lingkungan Tempat Tinggal'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 4: Aku Peduli Lingkungan Sekitar', 'Perilaku yang Baik di Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 4: Aku Peduli Lingkungan Sekitar', 'Norma dan Aturan di Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 5: Pancasila dalam Kehidupan Sehari-Hari', 'Mengingat Kembali 5 Sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 5: Pancasila dalam Kehidupan Sehari-Hari', 'Penerapan Sila di Rumah dan Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 5: Pancasila dalam Kehidupan Sehari-Hari', 'Pancasila dalam Perilaku Sehari-hari'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 6: Aku Anak yang Hebat dan Berakhlak Baik', 'Sikap Mandiri dan Tanggung Jawab'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 6: Aku Anak yang Hebat dan Berakhlak Baik', 'Sopan Santun dalam Bertutur Kata'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 1 (SD)', 'Semester 2', 'Bab 6: Aku Anak yang Hebat dan Berakhlak Baik', 'Anak yang Jujur dan Disiplin');

-- Grade 2
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 1: Mengenal Simbol-Simbol Pancasila', 'Simbol Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 1: Mengenal Simbol-Simbol Pancasila', 'Mengenal Bentuk dan Warna Simbol'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 1: Mengenal Simbol-Simbol Pancasila', 'Makna dari Setiap Simbol'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 2: Hubungan Simbol dan Sila Pancasila', 'Menyebutkan Bunyi Kelima Sila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 2: Hubungan Simbol dan Sila Pancasila', 'Hubungan Simbol dan Sila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 2: Hubungan Simbol dan Sila Pancasila', 'Contoh Perilaku Sesuai Sila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 3: Peran dan Tugas di Sekitar Kita', 'Peran dalam Keluarga'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 3: Peran dan Tugas di Sekitar Kita', 'Peran di Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 3: Peran dan Tugas di Sekitar Kita', 'Peran dalam Permainan dan Kegiatan Bersama'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 4: Hal-Hal Penting dalam Kehidupan Sehari-hari', 'Menjaga Kebersihan Diri dan Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 4: Hal-Hal Penting dalam Kehidupan Sehari-hari', 'Menjaga Kesehatan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 4: Hal-Hal Penting dalam Kehidupan Sehari-hari', 'Bersikap Sopan dan Santun'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 5: Menerapkan Nilai-Nilai Pancasila', 'Gotong Royong'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 5: Menerapkan Nilai-Nilai Pancasila', 'Keadilan dalam Pergaulan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 1', 'Bab 5: Menerapkan Nilai-Nilai Pancasila', 'Bermusyawarah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 1: Kita Beragam Tetapi Tetap Satu', 'Mengenal Identitas Diri dan Teman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 1: Kita Beragam Tetapi Tetap Satu', 'Menghargai Perbedaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 1: Kita Beragam Tetapi Tetap Satu', 'Gotong Royong dalam Keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 2: Negara Kesatuan Republik Indonesia', 'Aturan di Rumah dan Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 2: Negara Kesatuan Republik Indonesia', 'Musyawarah untuk Kebersamaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 2: Negara Kesatuan Republik Indonesia', 'Hak dan Kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 3: Simbol dan Nilai Dasar Negara', 'Lambang Negara Garuda Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 3: Simbol dan Nilai Dasar Negara', 'Bunyi dan Makna Sila-Sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 3: Simbol dan Nilai Dasar Negara', 'Mengenal Tokoh Perumus Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 4: Menjaga Keutuhan NKRI', 'Aturan di Lingkungan Sekitar'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 4: Menjaga Keutuhan NKRI', 'Musyawarah untuk Mufakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 2 (SD)', 'Semester 2', 'Bab 4: Menjaga Keutuhan NKRI', 'Menjaga Keutuhan NKRI');

-- Grade 3
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 1: Aku Anak Indonesia', 'Mengenal Identitas Diri'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 1: Aku Anak Indonesia', 'Ciri Khas dan Keunikan Budaya Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 1: Aku Anak Indonesia', 'Bangga Menjadi Anak Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 2: Aku Patuh Aturan', 'Aturan di Rumah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 2: Aku Patuh Aturan', 'Aturan di Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 2: Aku Patuh Aturan', 'Aturan di Masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 2: Aku Patuh Aturan', 'Akibat Melanggar Aturan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 3: Berbeda Itu Indah', 'Mengenal Keberagaman di Sekitar'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 3: Berbeda Itu Indah', 'Menghargai Perbedaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 3: Berbeda Itu Indah', 'Hidup Rukun dalam Keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 3: Berbeda Itu Indah', 'Toleransi sebagai Sikap Mulia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 4: Ayo Mengenal Pancasila', 'Mengenal Sila-Sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 4: Ayo Mengenal Pancasila', 'Lambang Negara: Garuda Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 4: Ayo Mengenal Pancasila', 'Pengamalan Sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 1', 'Bab 4: Ayo Mengenal Pancasila', 'Pancasila dalam Kehidupan Sehari-hari'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 1: Aku Anak Indonesia', 'Mengenal Diri sebagai Anak Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 1: Aku Anak Indonesia', 'Keberagaman Budaya di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 1: Aku Anak Indonesia', 'Menumbuhkan Rasa Cinta Tanah Air'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 2: Aku Patuh Aturan', 'Aturan di Rumah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 2: Aku Patuh Aturan', 'Aturan di Sekolah dan Masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 2: Aku Patuh Aturan', 'Pentingnya Menaati Aturan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 3: Berbeda Itu Indah', 'Mengenal Perbedaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 3: Berbeda Itu Indah', 'Menghargai Perbedaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 3: Berbeda Itu Indah', 'Toleransi dan Kerukunan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 4: Ayo Mengenal Pancasila', 'Mengenal dan Menghafal Sila-Sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 4: Ayo Mengenal Pancasila', 'Lambang Negara: Garuda Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 4: Ayo Mengenal Pancasila', 'Pengamalan Sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 5: Kerja Sama dalam Keberagaman', 'Pentingnya Kerja Sama'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 5: Kerja Sama dalam Keberagaman', 'Kerja Sama Meski Berbeda'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 5: Kerja Sama dalam Keberagaman', 'Mengatasi Perbedaan Pendapat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 6: Hak dan Kewajiban', 'Hak Sebagai Anak dan Siswa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 6: Hak dan Kewajiban', 'Kewajiban di Rumah dan Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 6: Hak dan Kewajiban', 'Menyeimbangkan Hak dan Kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 7: Mengenal Lingkungan Sekitar', 'Mengenal Wilayah Tempat Tinggal'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 7: Mengenal Lingkungan Sekitar', 'Menjaga Lingkungan Sekitar'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 7: Mengenal Lingkungan Sekitar', 'Bagian dari NKRI'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 8: Pengamalan Nilai-Nilai Pancasila dalam Kehidupan', 'Gotong Royong'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 8: Pengamalan Nilai-Nilai Pancasila dalam Kehidupan', 'Musyawarah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 3 (SD)', 'Semester 2', 'Bab 8: Pengamalan Nilai-Nilai Pancasila dalam Kehidupan', 'Keadilan dan Kepedulian');

-- Grade 4
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 1: Pancasila sebagai Nilai Kehidupan', 'Mengenal Arti dan Fungsi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 1: Pancasila sebagai Nilai Kehidupan', 'Nilai-Nilai dalam Setiap Sila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 1: Pancasila sebagai Nilai Kehidupan', 'Pengamalan Pancasila Sehari-hari'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 2: Konstitusi dan Norma di Masyarakat', 'Pengenalan Undang-Undang Dasar 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 2: Konstitusi dan Norma di Masyarakat', 'Norma dalam Kehidupan Bermasyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 2: Konstitusi dan Norma di Masyarakat', 'Menjadi Warga Negara yang Patuh Aturan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 3: Membangun Jati Diri dalam Kebhinekaan', 'Mengenal Keberagaman di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 3: Membangun Jati Diri dalam Kebhinekaan', 'Menghargai Perbedaan dan Membangun Persatuan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 3: Membangun Jati Diri dalam Kebhinekaan', 'Jati Diri Bangsa Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 4: Negaraku Indonesia', 'Mengenal Negara Kesatuan Republik Indonesia (NKRI)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 4: Negaraku Indonesia', 'Simbol-Simbol Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 4: Negaraku Indonesia', 'Cinta Tanah Air dan Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 5: Pola Hidup Bergotong Royong', 'Arti Gotong Royong'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 5: Pola Hidup Bergotong Royong', 'Bentuk-Bentuk Gotong Royong'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 1', 'Bab 5: Pola Hidup Bergotong Royong', 'Menerapkan Gotong Royong dalam Kehidupan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 1: Pancasila sebagai Dasar Negara', 'Memahami Makna Sila-Sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 1: Pancasila sebagai Dasar Negara', 'Nilai Kebersamaan dalam Perumusan Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 1: Pancasila sebagai Dasar Negara', 'Menghargai Pendapat dan Karya Orang Lain'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 2: Negara Kesatuan Republik Indonesia (NKRI)', 'Mengenal Bentuk dan Sistem Pemerintahan Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 2: Negara Kesatuan Republik Indonesia (NKRI)', 'Wilayah NKRI Menurut Undang-Undang Dasar'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 2: Negara Kesatuan Republik Indonesia (NKRI)', 'Faktor-Faktor Pemersatu Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 2: Negara Kesatuan Republik Indonesia (NKRI)', 'Menjaga Keutuhan NKRI di Lingkungan Sehari-hari'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 3: Norma-Norma di Masyarakat', 'Norma di Rumah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 3: Norma-Norma di Masyarakat', 'Norma di Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 3: Norma-Norma di Masyarakat', 'Norma di Masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 4: Hak dan Kewajiban sebagai Warga Negara', 'Hak Anak di Rumah dan Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 4: Hak dan Kewajiban sebagai Warga Negara', 'Kewajiban Anak di Rumah dan Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 4: Hak dan Kewajiban sebagai Warga Negara', 'Hak dan Kewajiban di Lingkungan Masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 5: Bangga Menjadi Anak Indonesia', 'Mengenal Identitas sebagai Anak Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 5: Bangga Menjadi Anak Indonesia', 'Meningkatkan Harga Diri Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 4 (SD)', 'Semester 2', 'Bab 5: Bangga Menjadi Anak Indonesia', 'Kegiatan yang Mengharumkan Nama Bangsa');

-- Grade 5
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 1', 'Bab 4: Perilaku yang Sesuai dengan Nilai-Nilai Pancasila', 'Menghormati Keragaman Agama'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 1', 'Bab 4: Perilaku yang Sesuai dengan Nilai-Nilai Pancasila', 'Menghargai Hak Asasi Manusia (HAM)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 1', 'Bab 4: Perilaku yang Sesuai dengan Nilai-Nilai Pancasila', 'Menghargai Keragaman Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 1', 'Bab 4: Perilaku yang Sesuai dengan Nilai-Nilai Pancasila', 'Mendukung Demokrasi di Lingkungan Sekitar'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 1', 'Bab 4: Perilaku yang Sesuai dengan Nilai-Nilai Pancasila', 'Memperjuangkan Kesetaraan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 1', 'Bab 5: Norma-Norma dalam Kehidupan Sehari-hari', 'Memahami Jenis-Jenis Norma'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 1', 'Bab 5: Norma-Norma dalam Kehidupan Sehari-hari', 'Norma dalam Keluarga dan Sekolah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 1', 'Bab 5: Norma-Norma dalam Kehidupan Sehari-hari', 'Norma di Masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 1', 'Bab 5: Norma-Norma dalam Kehidupan Sehari-hari', 'Pentingnya Mentaati Norma'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 2', 'Bab 3: Keragaman Budaya Indonesia', 'Keragaman Budaya sebagai Kekayaan Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 2', 'Bab 3: Keragaman Budaya Indonesia', 'Keanekaragaman Suku dan Bahasa Daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 2', 'Bab 3: Keragaman Budaya Indonesia', 'Adat Istiadat dan Kesenian Nusantara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 2', 'Bab 3: Keragaman Budaya Indonesia', 'Cinta dan Bangga terhadap Budaya Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 2', 'Bab 3: Keragaman Budaya Indonesia', 'Menghargai Perbedaan dan Menjaga Persatuan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 2', 'Bab 4: Aku dan Lingkungan Sekitarku', 'Makna Gotong Royong dalam Kehidupan Sehari-Hari'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 2', 'Bab 4: Aku dan Lingkungan Sekitarku', 'Manfaat Gotong Royong'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 2', 'Bab 4: Aku dan Lingkungan Sekitarku', 'Sikap Gotong Royong dalam Berbagai Lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 5 (SD)', 'Semester 2', 'Bab 4: Aku dan Lingkungan Sekitarku', 'Gotong Royong dan Nilai Pancasila');

-- Grade 6
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup Bangsa', 'Arti dan Makna Sila-sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup Bangsa', 'Penerapan Nilai Pancasila dalam Kehidupan Sehari-hari'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup Bangsa', 'Hubungan Antar Sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 2: Hak dan Kewajiban Warga Negara', 'Hak Asasi Manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 2: Hak dan Kewajiban Warga Negara', 'Kewajiban Sebagai Warga Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 2: Hak dan Kewajiban Warga Negara', 'Menghormati Hak Orang Lain'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 3: Persatuan dan Kesatuan dalam Keberagaman', 'Keberagaman Budaya di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 3: Persatuan dan Kesatuan dalam Keberagaman', 'Toleransi dan Hidup Rukun'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 3: Persatuan dan Kesatuan dalam Keberagaman', 'Gotong Royong sebagai Perekat Persatuan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 4: Sistem Pemerintahan Indonesia', 'Pembagian Kekuasaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 4: Sistem Pemerintahan Indonesia', 'Fungsi dan Peran Lembaga Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 4: Sistem Pemerintahan Indonesia', 'Undang-Undang Dasar 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 5: Peran Indonesia dalam Kancah Global', 'Kerja Sama Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 5: Peran Indonesia dalam Kancah Global', 'Politik Luar Negeri Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 6: Demokrasi, Pemilu, dan Pilkada', 'Pemilu sebagai Wujud Demokrasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 1', 'Bab 6: Demokrasi, Pemilu, dan Pilkada', 'Pilkada dan Partisipasi Masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 1: Pancasila sebagai Dasar Negara dan Ideologi Bangsa', 'Makna Pancasila sebagai Dasar Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 1: Pancasila sebagai Dasar Negara dan Ideologi Bangsa', 'Nilai-Nilai Pancasila sebagai Ideologi Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 2: Bhinneka Tunggal Ika', 'Makna Semboyan Bhinneka Tunggal Ika'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 2: Bhinneka Tunggal Ika', 'Menghargai Keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 2: Bhinneka Tunggal Ika', 'Persatuan dalam Perbedaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 3: Hak dan Kewajiban Warga Negara', 'Hak sebagai Warga Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 3: Hak dan Kewajiban Warga Negara', 'Kewajiban sebagai Warga Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 3: Hak dan Kewajiban Warga Negara', 'Saling Menghormati Hak dan Kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 4: Sistem Pemerintahan Indonesia', 'Sistem Pemerintahan Republik Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 4: Sistem Pemerintahan Indonesia', 'Pembagian Kekuasaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 5: Peran Indonesia dalam Lingkup Regional dan Global', 'Indonesia di Kawasan Asia Tenggara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 5: Peran Indonesia dalam Lingkup Regional dan Global', 'Peran Indonesia di Dunia Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 5: Peran Indonesia dalam Lingkup Regional dan Global', 'Pentingnya Kerja Sama Internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 6: Musyawarah dan Mufakat dalam Kehidupan Sehari-hari', 'Pengertian Musyawarah dan Mufakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 6: Musyawarah dan Mufakat dalam Kehidupan Sehari-hari', 'Penerapan Musyawarah di Lingkungan Sekitar'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 7: Kehidupan Berbangsa dan Bernegara', 'Cinta Tanah Air dan Nasionalisme'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 7: Kehidupan Berbangsa dan Bernegara', 'Menjaga Persatuan dan Kesatuan Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 6 (SD)', 'Semester 2', 'Bab 7: Kehidupan Berbangsa dan Bernegara', 'Partisipasi dalam Pembangunan Bangsa');

-- Grade 7
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Sejarah Kelahiran Pancasila', 'Latar Belakang Perumusan Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Sejarah Kelahiran Pancasila', 'Pembentukan BPUPKI dan PPKI'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Sejarah Kelahiran Pancasila', 'Rumusan Dasar Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 1: Sejarah Kelahiran Pancasila', 'Penetapan Pancasila sebagai Dasar Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Penerapan Nilai-Nilai Pancasila dalam Kehidupan', 'Nilai Ketuhanan (Sila 1)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Penerapan Nilai-Nilai Pancasila dalam Kehidupan', 'Nilai Kemanusiaan (Sila 2)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Penerapan Nilai-Nilai Pancasila dalam Kehidupan', 'Nilai Persatuan (Sila 3)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Penerapan Nilai-Nilai Pancasila dalam Kehidupan', 'Nilai Kerakyatan (Sila 4)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 2: Penerapan Nilai-Nilai Pancasila dalam Kehidupan', 'Nilai Keadilan (Sila 5)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Patuh Terhadap Norma', 'Pengertian dan Jenis-Jenis Norma'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Patuh Terhadap Norma', 'Contoh Penerapan Norma'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 3: Patuh Terhadap Norma', 'Menjaga Tertib Sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Keberagaman Bangsa Indonesia dalam Bingkai Bhinneka Tunggal Ika', 'Keberagaman Suku, Agama, Ras, dan Budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Keberagaman Bangsa Indonesia dalam Bingkai Bhinneka Tunggal Ika', 'Semboyan Bhinneka Tunggal Ika'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 4: Keberagaman Bangsa Indonesia dalam Bingkai Bhinneka Tunggal Ika', 'Menghargai Perbedaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 5: Wilayah Negara Kesatuan Republik Indonesia (NKRI)', 'Batas Wilayah Negara Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 5: Wilayah Negara Kesatuan Republik Indonesia (NKRI)', 'Pentingnya Menjaga Wilayah NKRI'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 1', 'Bab 5: Wilayah Negara Kesatuan Republik Indonesia (NKRI)', 'Wawasan Nusantara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 1: Keberagaman Bangsa Indonesia dalam Bingkai Bhinneka Tunggal Ika', 'Identifikasi Keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 1: Keberagaman Bangsa Indonesia dalam Bingkai Bhinneka Tunggal Ika', 'Makna Bhinneka Tunggal Ika'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 1: Keberagaman Bangsa Indonesia dalam Bingkai Bhinneka Tunggal Ika', 'Menghargai Keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 1: Keberagaman Bangsa Indonesia dalam Bingkai Bhinneka Tunggal Ika', 'Peran Aktif dalam Keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 2: Wilayah Negara Kesatuan Republik Indonesia', 'Batas Wilayah NKRI'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 2: Wilayah Negara Kesatuan Republik Indonesia', 'Karakteristik Daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 2: Wilayah Negara Kesatuan Republik Indonesia', 'Menjaga Kedaulatan dan Keutuhan Wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 3: Norma, Hukum, dan Peraturan dalam Kehidupan Bermasyarakat', 'Pengertian Norma, Hukum, dan Peraturan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 3: Norma, Hukum, dan Peraturan dalam Kehidupan Bermasyarakat', 'Pentingnya Mematuhi Aturan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 3: Norma, Hukum, dan Peraturan dalam Kehidupan Bermasyarakat', 'Peran Siswa dalam Menegakkan Norma dan Hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 4: Hak dan Kewajiban Warga Negara', 'Pengertian Hak dan Kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 4: Hak dan Kewajiban Warga Negara', 'Pentingnya Menyeimbangkan Hak dan Kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 4: Hak dan Kewajiban Warga Negara', 'Menghormati Hak Orang Lain'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Kerja Sama dalam Berbagai Bidang Kehidupan', 'Makna Kerja Sama'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Kerja Sama dalam Berbagai Bidang Kehidupan', 'Bentuk Kerja Sama di Lingkungan Siswa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 5: Kerja Sama dalam Berbagai Bidang Kehidupan', 'Kerja Sama sebagai Pengamalan Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Globalisasi dan Tantangannya terhadap Nilai Pancasila', 'Pengertian Globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Globalisasi dan Tantangannya terhadap Nilai Pancasila', 'Tantangan Globalisasi terhadap Jati Diri Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 7 (SMP)', 'Semester 2', 'Bab 6: Globalisasi dan Tantangannya terhadap Nilai Pancasila', 'Pancasila sebagai Filter Globalisasi');

-- Grade 8
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup Bangsa', 'Pancasila sebagai Dasar Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup Bangsa', 'Pancasila sebagai Pandangan Hidup'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup Bangsa', 'Fungsi dan Kedudukan Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup Bangsa', 'Nilai-Nilai dalam Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup Bangsa', 'Dinamika Perwujudan Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Bentuk dan Kedaulatan Negara', 'Bentuk Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Bentuk dan Kedaulatan Negara', 'Kedaulatan Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 2: Bentuk dan Kedaulatan Negara', 'Sistem Pemerintahan Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Tata Negara dan Pemerintahan', 'Lembaga-Lembaga Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Tata Negara dan Pemerintahan', 'Hubungan Antar Lembaga Negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 1', 'Bab 3: Tata Negara dan Pemerintahan', 'Penyelenggaraan Pemerintahan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Semangat Kebangkitan Nasional Tahun 1908', 'Kondisi Bangsa Indonesia Sebelum Tahun 1908'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Semangat Kebangkitan Nasional Tahun 1908', 'Perjuangan Bangsa Sebelum Tahun 1908'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Semangat Kebangkitan Nasional Tahun 1908', 'Peran Organisasi Pemuda'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 2', 'Bab 1: Semangat Kebangkitan Nasional Tahun 1908', 'Mewujudkan Persatuan Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Sumpah Pemuda dalam Bingkai Bhinneka Tunggal Ika', 'Latar Belakang Lahirnya Sumpah Pemuda'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Sumpah Pemuda dalam Bingkai Bhinneka Tunggal Ika', 'Isi dan Makna Ikrar Sumpah Pemuda'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 2', 'Bab 2: Sumpah Pemuda dalam Bingkai Bhinneka Tunggal Ika', 'Nilai-Nilai dalam Sumpah Pemuda'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Memperkuat Komitmen Kebangsaan', 'Semangat Pendiri Bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 8 (SMP)', 'Semester 2', 'Bab 3: Memperkuat Komitmen Kebangsaan', 'Perilaku Pelajar dalam Menjaga Keutuhan NKRI');

-- Grade 9
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Dinamika Perwujudan Pancasila dalam Kehidupan', 'Pancasila dalam praktik kehidupan berbangsa dan bernegara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Dinamika Perwujudan Pancasila dalam Kehidupan', 'Tantangan implementasi Pancasila di era globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Dinamika Perwujudan Pancasila dalam Kehidupan', 'Upaya mempertahankan nilai-nilai Pancasila dalam masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 1: Dinamika Perwujudan Pancasila dalam Kehidupan', 'Contoh perilaku sesuai nilai Pancasila di lingkungan keluarga, sekolah, dan masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Hubungan Pancasila dengan UUD Negara Republik Indonesia Tahun 1945', 'Pancasila sebagai dasar dan sumber dari segala sumber hukum negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Hubungan Pancasila dengan UUD Negara Republik Indonesia Tahun 1945', 'Peran Pancasila dalam penyusunan dan pelaksanaan UUD NRI 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Hubungan Pancasila dengan UUD Negara Republik Indonesia Tahun 1945', 'Contoh pasal-pasal UUD yang mencerminkan sila-sila Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 2: Hubungan Pancasila dengan UUD Negara Republik Indonesia Tahun 1945', 'Konsistensi nilai Pancasila dalam sistem ketatanegaraan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Hubungan Pancasila dengan Bhinneka Tunggal Ika', 'Arti penting semboyan Bhinneka Tunggal Ika'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Hubungan Pancasila dengan Bhinneka Tunggal Ika', 'Pancasila sebagai landasan dalam menyatukan keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Hubungan Pancasila dengan Bhinneka Tunggal Ika', 'Contoh penerapan nilai Pancasila dalam kehidupan multikultural'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 3: Hubungan Pancasila dengan Bhinneka Tunggal Ika', 'Menjaga toleransi, persatuan, dan keharmonisan dalam perbedaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Hubungan Pancasila dengan Negara Kesatuan Republik Indonesia (NKRI)', 'Pancasila sebagai ideologi pemersatu bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Hubungan Pancasila dengan Negara Kesatuan Republik Indonesia (NKRI)', 'Pancasila dalam memperkokoh keutuhan wilayah NKRI'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Hubungan Pancasila dengan Negara Kesatuan Republik Indonesia (NKRI)', 'Peran Pancasila dalam menghadapi ancaman disintegrasi bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 4: Hubungan Pancasila dengan Negara Kesatuan Republik Indonesia (NKRI)', 'Menumbuhkan sikap bela negara berdasarkan nilai-nilai Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Makna Pembukaan UUD Negara Republik Indonesia Tahun 1945', 'Pembukaan UUD 1945 sebagai sumber motivasi perjuangan bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Makna Pembukaan UUD Negara Republik Indonesia Tahun 1945', 'Tujuan negara menurut alinea-alinea Pembukaan UUD'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Makna Pembukaan UUD Negara Republik Indonesia Tahun 1945', 'Nilai-nilai universal dalam Pembukaan UUD (kemerdekaan, keadilan sosial, hak asasi)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 5: Makna Pembukaan UUD Negara Republik Indonesia Tahun 1945', 'Hubungan Pembukaan UUD dengan cita-cita nasional dan Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 6: Kedaulatan Negara Kesatuan Republik Indonesia', 'Pengertian dan prinsip kedaulatan (ke dalam dan ke luar)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 6: Kedaulatan Negara Kesatuan Republik Indonesia', 'Bentuk kedaulatan di negara demokrasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 6: Kedaulatan Negara Kesatuan Republik Indonesia', 'Cara negara menjalankan kekuasaan yang sah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 1', 'Bab 6: Kedaulatan Negara Kesatuan Republik Indonesia', 'Peran warga negara dalam menjaga kedaulatan negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Hakikat Hak dan Kewajiban Asasi Manusia', 'Pengertian hak asasi manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Hakikat Hak dan Kewajiban Asasi Manusia', 'Pengertian kewajiban asasi manusia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Hakikat Hak dan Kewajiban Asasi Manusia', 'Hak dan kewajiban sebagai satu kesatuan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Hakikat Hak dan Kewajiban Asasi Manusia', 'Sejarah perkembangan HAM di dunia dan Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 1: Hakikat Hak dan Kewajiban Asasi Manusia', 'Pentingnya pemenuhan hak dan kewajiban secara seimbang dalam kehidupan bermasyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Bentuk-bentuk pelanggaran hak dan pengingkaran kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Penyebab terjadinya pelanggaran hak dan kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Dampak pelanggaran hak dan pengingkaran kewajiban terhadap kehidupan sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Upaya mencegah dan mengatasi pelanggaran hak dan kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 2: Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Contoh kasus pelanggaran hak di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Nilai-nilai Pancasila dalam Sistem Pemerintahan', 'Sistem pemerintahan Indonesia: demokrasi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Nilai-nilai Pancasila dalam Sistem Pemerintahan', 'Pelaksanaan nilai-nilai Pancasila dalam lembaga eksekutif, legislatif, dan yudikatif'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Nilai-nilai Pancasila dalam Sistem Pemerintahan', 'Penerapan nilai musyawarah dan keadilan dalam kebijakan publik'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 3: Nilai-nilai Pancasila dalam Sistem Pemerintahan', 'Pentingnya akuntabilitas dan transparansi dalam pemerintahan yang berdasarkan Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Sistem dan Dinamika Demokrasi Pancasila', 'Pengertian demokrasi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Sistem dan Dinamika Demokrasi Pancasila', 'Prinsip-prinsip demokrasi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Sistem dan Dinamika Demokrasi Pancasila', 'Perkembangan sistem demokrasi di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Sistem dan Dinamika Demokrasi Pancasila', 'Tantangan pelaksanaan demokrasi di era globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 4: Sistem dan Dinamika Demokrasi Pancasila', 'Peran aktif warga negara dalam menjaga demokrasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Peran Indonesia dalam Perdamaian Dunia', 'Politik luar negeri bebas aktif'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Peran Indonesia dalam Perdamaian Dunia', 'Peran Indonesia dalam ASEAN, PBB, dan organisasi internasional lainnya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Peran Indonesia dalam Perdamaian Dunia', 'Sumbangsih Indonesia dalam penyelesaian konflik dan bantuan kemanusiaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Peran Indonesia dalam Perdamaian Dunia', 'Diplomasi budaya dan upaya menjaga perdamaian dunia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 9 (SMP)', 'Semester 2', 'Bab 5: Peran Indonesia dalam Perdamaian Dunia', 'Peran pelajar sebagai duta perdamaian');

-- Grade 10
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup', 'Sejarah perumusan Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup', 'Tokoh-tokoh perumus Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup', 'Arti penting Pancasila sebagai dasar negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup', 'Nilai-nilai dasar dalam kelima sila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 1: Pancasila sebagai Dasar Negara dan Pandangan Hidup', 'Penerapan nilai-nilai Pancasila dalam kehidupan pribadi, sekolah, masyarakat, dan negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945', 'Sejarah dan proses penyusunan UUD 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945', 'Sistematika dan struktur UUD NRI Tahun 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945', 'Fungsi dan kedudukan UUD dalam sistem ketatanegaraan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945', 'Perubahan (amendemen) UUD 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945', 'Hubungan UUD 1945 dengan Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Hak Asasi Manusia (HAM)', 'Pengertian dan makna HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Hak Asasi Manusia (HAM)', 'Sejarah perkembangan HAM di dunia dan Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Hak Asasi Manusia (HAM)', 'Jenis-jenis HAM (sipil, politik, ekonomi, sosial, budaya)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Hak Asasi Manusia (HAM)', 'Hak dan kewajiban warga negara dalam konteks HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Hak Asasi Manusia (HAM)', 'Perlindungan, penegakan, dan pelanggaran HAM di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 3: Hak Asasi Manusia (HAM)', 'Lembaga-lembaga terkait HAM (KOMNAS HAM, dll.)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 4: Demokrasi dan Partisipasi Politik', 'Pengertian demokrasi dan sejarah demokrasi di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 4: Demokrasi dan Partisipasi Politik', 'Nilai-nilai demokrasi dalam kehidupan berbangsa dan bernegara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 4: Demokrasi dan Partisipasi Politik', 'Sistem pemerintahan demokrasi di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 4: Demokrasi dan Partisipasi Politik', 'Pemilu dan peran partai politik'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 4: Demokrasi dan Partisipasi Politik', 'Bentuk partisipasi warga negara dalam proses demokrasi (hak pilih, organisasi, aspirasi politik)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 5: Persatuan dan Kesatuan Bangsa', 'Arti penting persatuan dan kesatuan bagi Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 5: Persatuan dan Kesatuan Bangsa', 'Tantangan dalam menjaga keutuhan bangsa di tengah keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 5: Persatuan dan Kesatuan Bangsa', 'Faktor penguat persatuan bangsa (Pancasila, Bahasa Indonesia, Bendera Merah Putih, dll.)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 5: Persatuan dan Kesatuan Bangsa', 'Sikap dan perilaku yang mencerminkan semangat persatuan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 5: Persatuan dan Kesatuan Bangsa', 'Upaya menjaga keutuhan NKRI di era globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 6: Norma, Hukum, dan Peraturan dalam Kehidupan Bermasyarakat', 'Pengertian norma, hukum, dan peraturan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 6: Norma, Hukum, dan Peraturan dalam Kehidupan Bermasyarakat', 'Jenis-jenis norma: agama, kesusilaan, kesopanan, dan hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 6: Norma, Hukum, dan Peraturan dalam Kehidupan Bermasyarakat', 'Fungsi norma dan hukum dalam kehidupan sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 6: Norma, Hukum, dan Peraturan dalam Kehidupan Bermasyarakat', 'Pentingnya mentaati norma dan hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 1', 'Bab 6: Norma, Hukum, dan Peraturan dalam Kehidupan Bermasyarakat', 'Sanksi bagi pelanggaran norma dan hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 1: Identitas Individu dan Kelompok', 'Pengertian identitas individu dan identitas kelompok'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 1: Identitas Individu dan Kelompok', 'Contoh perbedaan identitas dalam masyarakat Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 1: Identitas Individu dan Kelompok', 'Pentingnya menghargai perbedaan identitas'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 1: Identitas Individu dan Kelompok', 'Peran identitas dalam pembentukan karakter warga negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 2: Kolaborasi Antarbudaya', 'Pengertian kolaborasi dan kerja sama antarbudaya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 2: Kolaborasi Antarbudaya', 'Pentingnya interaksi antarbudaya dalam kehidupan sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 2: Kolaborasi Antarbudaya', 'Contoh keberhasilan kolaborasi antarbudaya di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 2: Kolaborasi Antarbudaya', 'Tantangan dan solusi dalam membangun kolaborasi antarbudaya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 3: Pancasila dan Kebhinekaan', 'Kebhinekaan Indonesia: suku, budaya, bahasa, agama'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 3: Pancasila dan Kebhinekaan', 'Peran Pancasila dalam mempersatukan keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 3: Pancasila dan Kebhinekaan', 'Pancasila sebagai alat pemersatu bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 3: Pancasila dan Kebhinekaan', 'Mengelola kebhinekaan sebagai modal sosial pembangunan nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 4: NKRI dalam Konteks Bentuk Pemerintahan', 'Pengertian NKRI dan sejarah pembentukannya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 4: NKRI dalam Konteks Bentuk Pemerintahan', 'Bentuk pemerintahan Republik Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 4: NKRI dalam Konteks Bentuk Pemerintahan', 'Sistem pemerintahan presidensial'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 4: NKRI dalam Konteks Bentuk Pemerintahan', 'Peran serta masyarakat dalam menjaga keutuhan NKRI'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 5: Desentralisasi dan Otonomi Daerah', 'Pengertian desentralisasi dan otonomi daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 5: Desentralisasi dan Otonomi Daerah', 'Tujuan otonomi daerah dalam sistem pemerintahan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 5: Desentralisasi dan Otonomi Daerah', 'Contoh penerapan otonomi daerah di berbagai wilayah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 5: Desentralisasi dan Otonomi Daerah', 'Hubungan antara pemerintah pusat dan daerah'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 6: Hubungan Antar Perundang-Undangan', 'Hierarki peraturan perundang-undangan di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 6: Hubungan Antar Perundang-Undangan', 'Urutan peraturan: UUD 1945, UU, PP, Perpres, Perda, dll.'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 6: Hubungan Antar Perundang-Undangan', 'Contoh penerapan dan konflik norma hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 6: Hubungan Antar Perundang-Undangan', 'Peran warga negara dalam menaati peraturan hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 7: Proyek Gotong Royong Kewarganegaraan', 'Pengertian gotong royong dalam konteks kewarganegaraan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 7: Proyek Gotong Royong Kewarganegaraan', 'Perencanaan dan pelaksanaan proyek kolaboratif'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 7: Proyek Gotong Royong Kewarganegaraan', 'Refleksi hasil proyek dan pembelajaran karakter'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 7: Proyek Gotong Royong Kewarganegaraan', 'Menumbuhkan semangat kepedulian sosial dan tanggung jawab'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 8: Pancasila sebagai Dasar Negara dan Pandangan Hidup', 'Pancasila sebagai dasar penyelenggaraan negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 8: Pancasila sebagai Dasar Negara dan Pandangan Hidup', 'Nilai-nilai Pancasila sebagai panduan hidup berbangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 8: Pancasila sebagai Dasar Negara dan Pandangan Hidup', 'Pancasila dalam kehidupan pribadi dan masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 8: Pancasila sebagai Dasar Negara dan Pandangan Hidup', 'Aktualisasi nilai-nilai Pancasila dalam era modern'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 9: UUD NRI Tahun 1945 dan Sistem Ketatanegaraan', 'Sistematika dan isi pokok UUD 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 9: UUD NRI Tahun 1945 dan Sistem Ketatanegaraan', 'Fungsi UUD dalam sistem hukum dan pemerintahan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 9: UUD NRI Tahun 1945 dan Sistem Ketatanegaraan', 'Lembaga-lembaga negara menurut UUD 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 9: UUD NRI Tahun 1945 dan Sistem Ketatanegaraan', 'Konstitusi dan pelaksanaan demokrasi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 10: Hak Asasi Manusia dan Implementasinya', 'Jenis-jenis HAM dan perlindungannya di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 10: Hak Asasi Manusia dan Implementasinya', 'Lembaga penegak HAM (KOMNAS HAM, Pengadilan HAM)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 10: Hak Asasi Manusia dan Implementasinya', 'Studi kasus pelanggaran HAM di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 10: Hak Asasi Manusia dan Implementasinya', 'Peran warga negara dalam menjunjung HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 11: Demokrasi dan Partisipasi Politik', 'Pengertian demokrasi dan ciri-cirinya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 11: Demokrasi dan Partisipasi Politik', 'Sistem demokrasi di Indonesia (langsung, tidak langsung)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 11: Demokrasi dan Partisipasi Politik', 'Partisipasi warga negara dalam Pemilu dan kehidupan politik'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 10 (SMA)', 'Semester 2', 'Bab 11: Demokrasi dan Partisipasi Politik', 'Nilai-nilai demokrasi dalam kehidupan berbangsa');

-- Grade 11
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 1: Pemikiran Pendiri Bangsa tentang Pancasila', 'Gagasan tokoh-tokoh perumus dasar negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 1: Pemikiran Pendiri Bangsa tentang Pancasila', 'Hubungan Pancasila dengan nilai-nilai luhur bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 1: Pemikiran Pendiri Bangsa tentang Pancasila', 'Pandangan tentang hubungan agama dan negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 2: Penerapan Pancasila dalam Kehidupan', 'Pengamalan nilai-nilai Pancasila dalam kehidupan pribadi dan sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 2: Penerapan Pancasila dalam Kehidupan', 'Peran Pancasila dalam menghadapi tantangan modern'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 2: Penerapan Pancasila dalam Kehidupan', 'Contoh konkret penerapan sila-sila Pancasila di masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 3: Peluang dan Tantangan Penerapan Pancasila di Era Global', 'Tantangan nilai Pancasila di tengah globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 3: Peluang dan Tantangan Penerapan Pancasila di Era Global', 'Dampak pengaruh budaya luar terhadap jati diri bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 3: Peluang dan Tantangan Penerapan Pancasila di Era Global', 'Strategi penguatan nilai Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 4: Proyek Gotong Royong Kewarganegaraan', 'Konsep gotong royong dalam kehidupan warga negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 4: Proyek Gotong Royong Kewarganegaraan', 'Pelaksanaan proyek kolaboratif berbasis nilai Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 4: Proyek Gotong Royong Kewarganegaraan', 'Refleksi sikap aktif sebagai warga negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 5: Ide Pendiri Bangsa tentang Konstitusi', 'Pandangan tokoh pendiri bangsa mengenai konstitusi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 5: Ide Pendiri Bangsa tentang Konstitusi', 'Prinsip-prinsip dasar konstitusi Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 5: Ide Pendiri Bangsa tentang Konstitusi', 'Konstitusi sebagai dasar hukum tertinggi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 6: Hubungan Antarregulasi di Indonesia', 'Hirarki peraturan perundang-undangan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 6: Hubungan Antarregulasi di Indonesia', 'Kesesuaian peraturan dengan UUD 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 6: Hubungan Antarregulasi di Indonesia', 'Penegakan hukum berdasarkan sistem regulasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 7: Hak dan Kewajiban Asasi Manusia dalam Pancasila', 'Jenis dan substansi HAM menurut nilai-nilai Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 7: Hak dan Kewajiban Asasi Manusia dalam Pancasila', 'Perbedaan hak dan kewajiban warga negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 7: Hak dan Kewajiban Asasi Manusia dalam Pancasila', 'Peran negara dalam menjamin HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 8: Perlindungan dan Penegakan HAM di Indonesia', 'Lembaga perlindungan HAM di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 8: Perlindungan dan Penegakan HAM di Indonesia', 'Contoh pelanggaran HAM dan upaya penyelesaiannya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 8: Perlindungan dan Penegakan HAM di Indonesia', 'Peran masyarakat dalam menegakkan HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 9: Sistem dan Dinamika Demokrasi Pancasila', 'Pengertian dan prinsip demokrasi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 9: Sistem dan Dinamika Demokrasi Pancasila', 'Ciri khas demokrasi di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 9: Sistem dan Dinamika Demokrasi Pancasila', 'Perkembangan sistem demokrasi Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 10: Demokrasi dan Partisipasi Politik Warga Negara', 'Bentuk partisipasi politik warga (pemilu, organisasi, aspirasi)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 10: Demokrasi dan Partisipasi Politik Warga Negara', 'Pentingnya kesadaran politik dan civic engagement'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 10: Demokrasi dan Partisipasi Politik Warga Negara', 'Peran pemuda dalam demokrasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 11: Peran Indonesia dalam Perdamaian Dunia', 'Kebijakan luar negeri Indonesia bebas aktif'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 11: Peran Indonesia dalam Perdamaian Dunia', 'Partisipasi Indonesia dalam perdamaian global'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 11: Peran Indonesia dalam Perdamaian Dunia', 'Diplomasi Indonesia dalam forum internasional'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 12: Sistem Hukum dan Peradilan di Indonesia', 'Struktur sistem hukum Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 12: Sistem Hukum dan Peradilan di Indonesia', 'Peran lembaga peradilan: MA, MK, KY'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 12: Sistem Hukum dan Peradilan di Indonesia', 'Fungsi hukum dalam kehidupan masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 13: Hukum dan Keadilan sebagai Penopang Kehidupan Bangsa', 'Makna keadilan dalam hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 13: Hukum dan Keadilan sebagai Penopang Kehidupan Bangsa', 'Keadilan sosial dan supremasi hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 13: Hukum dan Keadilan sebagai Penopang Kehidupan Bangsa', 'Etika dalam penegakan hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 14: Menjaga Keutuhan Negara Kesatuan Republik Indonesia', 'Pentingnya menjaga NKRI dari ancaman disintegrasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 14: Menjaga Keutuhan Negara Kesatuan Republik Indonesia', 'Peran warga negara dalam memperkuat persatuan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 14: Menjaga Keutuhan Negara Kesatuan Republik Indonesia', 'Konsep bela negara di berbagai lingkungan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 15: Harmoni dalam Keberagaman (Bhinneka Tunggal Ika)', 'Pentingnya sikap saling menghargai dalam perbedaan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 15: Harmoni dalam Keberagaman (Bhinneka Tunggal Ika)', 'Perbedaan sebagai kekuatan bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 15: Harmoni dalam Keberagaman (Bhinneka Tunggal Ika)', 'Kolaborasi dalam keberagaman sosial dan budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 16: Ancaman terhadap Indonesia dan Strategi Penanggulangan', 'Jenis ancaman: fisik, non-fisik, ideologi, budaya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 16: Ancaman terhadap Indonesia dan Strategi Penanggulangan', 'Upaya pertahanan dan ketahanan nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 1', 'Bab 16: Ancaman terhadap Indonesia dan Strategi Penanggulangan', 'Peran aktif masyarakat dalam mencegah ancaman terhadap NKRI'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 1: Hak Asasi Manusia (HAM)', 'Pengertian dan prinsip-prinsip HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 1: Hak Asasi Manusia (HAM)', 'Perlindungan dan pemenuhan HAM di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 1: Hak Asasi Manusia (HAM)', 'Peran lembaga negara dan masyarakat dalam penegakan HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 1: Hak Asasi Manusia (HAM)', 'Contoh pelanggaran HAM dan penanganannya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 2: Sistem dan Dinamika Demokrasi Pancasila', 'Hakikat demokrasi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 2: Sistem dan Dinamika Demokrasi Pancasila', 'Prinsip-prinsip demokrasi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 2: Sistem dan Dinamika Demokrasi Pancasila', 'Sistem pemerintahan demokratis di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 2: Sistem dan Dinamika Demokrasi Pancasila', 'Perkembangan demokrasi Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 2: Sistem dan Dinamika Demokrasi Pancasila', 'Tantangan dan peluang demokrasi di era global'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 3: Sistem Hukum dan Peradilan di Indonesia', 'Pengertian hukum dan peradilan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 3: Sistem Hukum dan Peradilan di Indonesia', 'Jenis-jenis hukum yang berlaku di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 3: Sistem Hukum dan Peradilan di Indonesia', 'Struktur sistem peradilan di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 3: Sistem Hukum dan Peradilan di Indonesia', 'Peran lembaga peradilan dalam penegakan hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 3: Sistem Hukum dan Peradilan di Indonesia', 'Tantangan dan perbaikan sistem hukum nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 4: Peran Indonesia dalam Perdamaian Dunia', 'Keikutsertaan Indonesia dalam organisasi internasional (PBB, ASEAN, dll.)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 4: Peran Indonesia dalam Perdamaian Dunia', 'Diplomasi Indonesia dalam penyelesaian konflik global'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 4: Peran Indonesia dalam Perdamaian Dunia', 'Keterlibatan Indonesia dalam misi perdamaian dunia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 4: Peran Indonesia dalam Perdamaian Dunia', 'Bentuk kerja sama internasional yang dilakukan Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 5: Ancaman terhadap Indonesia', 'Jenis ancaman: ideologi, politik, ekonomi, sosial budaya, dan pertahanan keamanan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 5: Ancaman terhadap Indonesia', 'Penyebab dan dampak ancaman terhadap integrasi nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 5: Ancaman terhadap Indonesia', 'Strategi pertahanan nasional menghadapi ancaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 5: Ancaman terhadap Indonesia', 'Peran warga negara dalam menjaga keutuhan NKRI'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 6: Pancasila sebagai Ideologi Negara', 'Makna dan nilai-nilai dalam ideologi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 6: Pancasila sebagai Ideologi Negara', 'Fungsi Pancasila sebagai dasar berbangsa dan bernegara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 6: Pancasila sebagai Ideologi Negara', 'Implementasi nilai Pancasila dalam kehidupan nyata'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 6: Pancasila sebagai Ideologi Negara', 'Peluang dan tantangan penerapan ideologi Pancasila'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 11 (SMA)', 'Semester 2', 'Bab 6: Pancasila sebagai Ideologi Negara', 'Proyek gotong royong kewarganegaraan (aksi nyata pelajar Pancasila)');

-- Grade 12
INSERT INTO public.curriculum (curriculum_type, language, subject, grade, semester, chapter, topic)
VALUES
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 1: Ber-Pancasila dalam Keseharian di Masyarakat', 'Konsep “Saya dan Pancasila”'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 1: Ber-Pancasila dalam Keseharian di Masyarakat', 'Contoh implementasi nilai-nilai Pancasila dalam kehidupan pribadi, keluarga, sekolah, dan masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 1: Ber-Pancasila dalam Keseharian di Masyarakat', 'Refleksi dan praktik nilai Pancasila dalam berinteraksi sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 1: Ber-Pancasila dalam Keseharian di Masyarakat', 'Rencana dan pelaporan portofolio penerapan nilai-nilai Pancasila dalam kegiatan sehari-hari'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 2: Ber-Pancasila dalam Kehidupan Global', 'Kekuatan dan peluang bangsa Indonesia dalam menghadapi globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 2: Ber-Pancasila dalam Kehidupan Global', 'Kelemahan dan tantangan bangsa Indonesia di era global'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 2: Ber-Pancasila dalam Kehidupan Global', 'Peran nilai-nilai Pancasila sebagai pedoman dalam menghadapi pengaruh global (budaya, politik, ekonomi)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 2: Ber-Pancasila dalam Kehidupan Global', 'Penerapan nilai gotong royong, keadilan sosial, dan kemanusiaan dalam skala global'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 3: Hak dan Kewajiban Warga Negara', 'Pengertian dan ruang lingkup hak warga negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 3: Hak dan Kewajiban Warga Negara', 'Kewajiban utama warga negara dalam kehidupan berbangsa dan bernegara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 3: Hak dan Kewajiban Warga Negara', 'Contoh penerapan keseimbangan antara hak dan kewajiban dalam kehidupan nyata'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 3: Hak dan Kewajiban Warga Negara', 'Upaya pemerintah dan masyarakat dalam menjamin pemenuhan hak dan pelaksanaan kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 4: Kasus Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Pengertian pelanggaran hak dan pengingkaran kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 4: Kasus Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Faktor penyebab terjadinya pelanggaran hak dan pengingkaran kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 4: Kasus Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Dampak dari pelanggaran hak dan kewajiban terhadap kehidupan sosial dan bernegara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 4: Kasus Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Contoh kasus pelanggaran hak/kewajiban di Indonesia dan analisis penyelesaiannya'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 4: Kasus Pelanggaran Hak dan Pengingkaran Kewajiban Warga Negara', 'Upaya pencegahan dan penanganan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 5: Peran Lembaga Negara dalam Menjamin Hak dan Kewajiban Warga', 'Fungsi dan peran lembaga-lembaga negara dalam sistem ketatanegaraan Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 5: Peran Lembaga Negara dalam Menjamin Hak dan Kewajiban Warga', '(MPR, DPR, DPD, Presiden/Wakil Presiden, MA, MK, KY, BPK)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 5: Peran Lembaga Negara dalam Menjamin Hak dan Kewajiban Warga', 'Peran lembaga penegak hukum dalam menjamin keadilan dan pelindungan hak warga'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 5: Peran Lembaga Negara dalam Menjamin Hak dan Kewajiban Warga', 'Mekanisme pengaduan dan pelaporan pelanggaran hak asasi manusia atau hak warga negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 1', 'Bab 5: Peran Lembaga Negara dalam Menjamin Hak dan Kewajiban Warga', 'Kolaborasi antar lembaga negara dan masyarakat dalam menjaga demokrasi dan keadilan sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 1: Pancasila sebagai Dasar Negara', 'Makna dan fungsi Pancasila sebagai dasar negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 1: Pancasila sebagai Dasar Negara', 'Nilai-nilai Pancasila dalam kehidupan berbangsa dan bernegara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 1: Pancasila sebagai Dasar Negara', 'Contoh penerapan nilai Pancasila di berbagai bidang kehidupan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945', 'Sejarah perumusan UUD 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945', 'Fungsi dan kedudukan UUD 1945 dalam sistem hukum nasional'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 2: Undang-Undang Dasar Negara Republik Indonesia Tahun 1945', 'Pasal-pasal penting terkait hak dan kewajiban warga negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 3: Negara Kesatuan Republik Indonesia (NKRI)', 'Pengertian negara kesatuan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 3: Negara Kesatuan Republik Indonesia (NKRI)', 'Ciri-ciri dan bentuk negara Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 3: Negara Kesatuan Republik Indonesia (NKRI)', 'Pentingnya menjaga keutuhan NKRI'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 4: Bhinneka Tunggal Ika', 'Keberagaman suku, agama, ras, dan bahasa di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 4: Bhinneka Tunggal Ika', 'Prinsip Bhinneka Tunggal Ika sebagai perekat bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 4: Bhinneka Tunggal Ika', 'Contoh sikap menjaga persatuan dalam keberagaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 5: Persatuan dan Kesatuan Bangsa', 'Dinamika persatuan dan kesatuan bangsa dari masa ke masa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 5: Persatuan dan Kesatuan Bangsa', 'Tantangan terhadap persatuan bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 5: Persatuan dan Kesatuan Bangsa', 'Strategi memperkuat semangat persatuan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 6: Norma, Hukum, dan Peraturan', 'Pengertian dan jenis-jenis norma'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 6: Norma, Hukum, dan Peraturan', 'Fungsi hukum dan peraturan dalam masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 6: Norma, Hukum, dan Peraturan', 'Pentingnya ketaatan terhadap hukum'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 7: Hak Asasi Manusia (HAM)', 'Konsep dan prinsip-prinsip HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 7: Hak Asasi Manusia (HAM)', 'Jenis-jenis HAM'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 7: Hak Asasi Manusia (HAM)', 'Jaminan dan perlindungan HAM di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 8: Kebutuhan Warga Negara', 'Kebutuhan dasar (sandang, pangan, papan)'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 8: Kebutuhan Warga Negara', 'Kebutuhan sosial dan partisipasi warga negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 8: Kebutuhan Warga Negara', 'Peran negara dalam pemenuhan kebutuhan warga'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 9: Konstitusi Negara', 'Pengertian dan fungsi konstitusi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 9: Konstitusi Negara', 'Hubungan konstitusi dengan UUD 1945'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 9: Konstitusi Negara', 'Konstitusi sebagai dasar pengaturan kehidupan bernegara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 10: Kekuasaan dan Politik', 'Konsep kekuasaan dalam negara'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 10: Kekuasaan dan Politik', 'Sistem politik dan demokrasi di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 10: Kekuasaan dan Politik', 'Partisipasi politik masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 11: Globalisasi', 'Pengaruh globalisasi terhadap budaya, ekonomi, dan politik'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 11: Globalisasi', 'Dampak positif dan negatif globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 11: Globalisasi', 'Sikap bijak dalam menghadapi globalisasi'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 12: Dinamika Persatuan dan Kesatuan Bangsa', 'Perubahan dan tantangan terhadap kesatuan bangsa'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 12: Dinamika Persatuan dan Kesatuan Bangsa', 'Upaya mempertahankan keutuhan NKRI di tengah perubahan zaman'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 12: Dinamika Persatuan dan Kesatuan Bangsa', 'Peran generasi muda dalam menjaga persatuan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 13: Pengaruh Kemajuan IPTEK (Ilmu Pengetahuan dan Teknologi)', 'Perkembangan teknologi dan dampaknya pada masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 13: Pengaruh Kemajuan IPTEK (Ilmu Pengetahuan dan Teknologi)', 'Potensi dan risiko IPTEK'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 13: Pengaruh Kemajuan IPTEK (Ilmu Pengetahuan dan Teknologi)', 'Cara menyikapi perkembangan IPTEK secara positif'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 14: Kasus Pelanggaran Hak dan Pengingkaran Kewajiban', 'Jenis dan contoh pelanggaran HAM dan pengingkaran kewajiban'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 14: Kasus Pelanggaran Hak dan Pengingkaran Kewajiban', 'Dampak pelanggaran terhadap kehidupan sosial'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 14: Kasus Pelanggaran Hak dan Pengingkaran Kewajiban', 'Upaya penyelesaian dan pencegahan'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 15: Perlindungan dan Penegakan Hukum', 'Lembaga penegak hukum di Indonesia'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 15: Perlindungan dan Penegakan Hukum', 'Fungsi dan peran lembaga hukum dalam masyarakat'),
('Kurikulum Merdeka Belajar', 'id', 'Pendidikan Pancasila', 'Grade 12 (SMA)', 'Semester 2', 'Bab 15: Perlindungan dan Penegakan Hukum', 'Strategi penegakan hukum yang adil dan transparan');
